### ISSUE TITLE
. net framework support

### ISSUE THREAD

**Issue by zhongshuiyuan** [MaxRev-Dev/gdal.netcore#10]
Will. Net framework be supported in the future？

**Comment by MaxRev-Dev** [comment]
No. I did not planned to support .NET Framework.  There are some [official nuget packages](https://www.nuget.org/profiles/szekerest)

**Comment by zhongshuiyuan** [comment]
Yes, but the version only stays at 204。

**Comment by MaxRev-Dev** [comment]
This unofficial packages created especially for .NET Core runtime. Targeting to archaic .NET Framework requires a lot of work and patience. Vise versa, I want to make it modern and maintainable for Unix and support virtualization.
