### ISSUE TITLE
Receiving runtime exception when reading TIFF files with ZSTD compression on Linux.

### ISSUE THREAD

**Issue by janondracek** [MaxRev-Dev/gdal.netcore#105]
Hi Team,

We have a .NET 6.0 web api application that leverages the following Gdal Core packages:

		<PackageReference Include="MaxRev.Gdal.Core" Version="3.6.1.120" />
		<PackageReference Include="MaxRev.Gdal.LinuxRuntime.Minimal" Version="3.6.1.100" />

We use it to read data from TIFF files compressed in ZSTD compression. Unfortunately, on Linux using the above listed dependencies we are receiving the following error:
“Cannot open TIFF file due to missing codec ZSTD.”

This does not happened and all works fine when we run on Windows and use the following dependencies.

		<PackageReference Include="MaxRev.Gdal.Core" Version="3.6.1.120" />
		<PackageReference Include="MaxRev.Gdal.WindowsRuntime.Minimal" Version="3.6.1.110" />

We would still like to run on Linux. Is there some setup we can make in order to make it work for Linux as well?

Thanks a lot

Regards

Jan

**Comment by MaxRev-Dev** [comment]
You have to clarify these points:
Which version of the packages could be affected, is it 3.6.1?
Which Linux distro you are running on?

Also, there could an issue with your distro, as:
1. We have 3.7.0 released a few weeks ago. Please consider updating the packages.
2. I can assure you that MaxRev.Gdal.LinuxRuntime.Minimal package of version 3.6.1 contains libz.so, also the Linux workflow CI passed, and the packages were tested for this version. No breaking changes were applied to dependencies.
3. Try to install `zlib` ([issue](https://stackoverflow.com/questions/72266945/gdal-3-4-1-build-cannot-create-tiff-file-due-to-missing-codec-for-deflate)).
4. If you have a specific file, you can attach it here with a minimal repro sample.

**Comment by MaxRev-Dev** [comment]
UPD: That's not a bug. Regarding the [tiff library can have](https://github.com/microsoft/vcpkg/issues/27247) a dependency on zlib, this can be configured as an additional option ([here](https://github.com/MaxRev-Dev/gdal.netcore/blob/v3.6.1/shared/GdalCore.opt#L27)).
This extension could be added to the next release.

**Comment by janondracek** [comment]
Hello MaxRev-Dev team,

Thank you for your reply. I will try to clarify the listed points:

1) We are using version 3.6.1. We will try to update the package and update the thread here.
2) We are running into the problem in a Docker container based on base image mcr.microsoft.com/dotnet/aspnet:6.0

Thank you

Kind regards

Jan

**Comment by janondracek** [comment]
UPD: The issue in a Linux Docker container persists even after updating core and runtime libraries to 3.7.0. “Cannot open TIFF file due to missing codec ZSTD.”

**Comment by janondracek** [comment]
Hello MaxRev-Dev team, 

thanks for your answer and confirmation. It would be great if the feature was added in one of the next releases.

Kind regards

Jan
