### ISSUE TITLE
Linux ARM64 package ?

### ISSUE THREAD

**Issue by hu-xd** [MaxRev-Dev/gdal.netcore#106]
**Is your feature request related to a problem? Please describe.**
no Nuget package available for Linux ARM64 platform

**Describe the solution you'd like or your ideas here**
publish Nuget package for Linux ARM64 platform

**Additional context**
no

**Comment by MaxRev-Dev** [comment]
No.

It would be nice to have some context why you need it and a good description of the issue. 
Honestly, I don't have any resources to support that architecture. There is no [GH runner ](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) on Linux-arm64. In addition, I need a self-hosted arm64 Linux machine. One option is to use [QEMU](https://github.com/marketplace/actions/run-on-architecture). 
If you have time and want, you can feel free to contribute. But for now, I suggest building it on your target machine.

**Comment by hu-xd** [comment]
alright I didn't know GH runner doesn't support Linux-ARM64 yet, I'll follow that issue first 🙂

**Comment by hu-xd** [comment]
ARM version of GitHub runner is in preview :-), would this help ?
https://resources.github.com/devops/accelerate-your-cicd-with-arm-and-gpu-runners-in-github-actions/
