### ISSUE TITLE
GDAL_DISABLE_READDIR_ON_OPEN config

### ISSUE THREAD

**Issue by janondracek** [MaxRev-Dev/gdal.netcore#108]
**Is your feature request related to a problem? Please describe.**
Is there a way how to set GDAL global configuration options for GDAL_DISABLE_READDIR_ON_OPEN ? I suppose the current default is FALSE whereas  we would need TRUE.

**Describe the solution you'd like or your ideas here**
A way to setup the configuration.

**Additional context**
https://gdal.org/user/configoptions.html (Performance and caching)

**Comment by MaxRev-Dev** [comment]
Yes. You can set this option with `Gdal.SetConfigOption("GDAL_DISABLE_READDIR_ON_OPEN", true);` The API of C# bindings is straightforward and similar to a C/C++ one. Please look at the documentation before creating such issues. Also, I recommend you enable IntelliSense in VSCode or your IDE.
