### ISSUE TITLE
GDAL band data types missing from ReadRaster() overloads 

### ISSUE THREAD

**Issue by twest820** [MaxRev-Dev/gdal.netcore#111]
**Is your feature request related to a problem? Please describe.**
`Band` and `Dataset` currently expose overloads for `byte`, `double`, `float`, `int`, and `short`. Overloads for `byte`, `ushort` and `uint` are missing, along with less commonly used GDAL datatypes such as `GDT_Int8`, `GDT_Int64`, `GDT_UInt64`, `GDT_CFloat32`, `GDT_CFloat64`, `GDT_CInt16`, and `GDT_CInt32`. Some avoidable hoop jumping is therefore needed to read rasters with these datatypes.

**Describe the solution you'd like or your ideas here**
Since these are all just differently typed ways of moving bytes around, adding overloads for several of the remaining GDAL datatypes appears straightforward. 
```
ReadRaster(..., sbyte buffer, ...)
ReadRaster(..., Int64 buffer, ...)
ReadRaster(..., UInt16 buffer, ...)
ReadRaster(..., UInt32 buffer, ...)
ReadRaster(..., UInt64 buffer, ...)
ReadRaster(..., Complex buffer, ...)
```
I'd suggest also
```
ReadRaster<TBand>(..., TBand buffer, ...) where TBand : INumber<TBand>
```
to compose with .NET 7, though some minor checking is needed to exclude types implementing `INumber` which lack corresponding GDAL support.

Not seeing `System.Numerics` has equivalents of `GDT_CFloat32`, `GDT_CInt16`, or `GDT_CInt32`—a `Complex<T>` appears to be absent.

**Additional context**
My guess is `UInt16` support is probably most valuable as it's frequently used with images.  GDAL's GTiff driver doesn't currently support `Int8` (`sbyte`), `Int64`, or `UInt64` so those seem low priority.

A workaround I've had success with is to use `Unsafe` to bend the type to one of the same size. _E.g._
```
                case DataType.GDT_UInt16:
                    rasterDataset.ReadRaster(xOff: 0, yOff: 0, xSize: this.XSize, ySize: this.YSize, Unsafe.As<Int16[]>(this.Data), buf_xSize: this.XSize, buf_ySize: this.YSize, this.Bands.Length, bandMap, pixelSpace: 0, lineSpace: 0, bandSpace: 0);
```

**Comment by MaxRev-Dev** [comment]
I have no control over this. Introducing some workarounds can be dangerous and "unsafe". This library does not extend or change GDAL's behaviour. 
As this issue is related directly to GDAL's bindings, please consider creating an issue in GDAL's repo.
I found a similar PR for Java bindings here https://github.com/OSGeo/gdal/pull/7893. I believe this can be implemented in a similar manner.

**Comment by MaxRev-Dev** [comment]
The issue from the GDAL repo can be linked to this one. After it completes in GDAL's release it will be pulled up here. As for now, I'm closing this.

**Comment by twest820** [comment]
Hmm, any sense of how long a fix might take to flow? The Java PR merged last August but gdal_csharp.i still hasn't updated in master or the 3.8 release branch.

Workaround above continues to work fine for read but this is rather a blocker for write (type bending fails as the .tif gets marked, reasonably, as having that datatype).

**Comment by twest820** [comment]
Yes, hence the question when (if?) such code motion might occur. Which follows from the above in this issue

> After it completes in GDAL's release it will be pulled up here.

**Comment by MaxRev-Dev** [comment]
Around a few days/weeks after the GDAL release and could be per request, as I can miss the date. I'm running the pipelines with self-hosted machines and have no profit from it.

**Comment by twest820** [comment]
Cool. Is there a way to find out when that GDAL release will happen? Didn't see anything tracking corresponding C# changes in the OSGeo repo when I searched a few days ago, though I might not have hit on the right keywords.

It's not that there aren't some workarounds—such as writing 32 bit signed integer and converting to 16 bit unsigned with tools which do have access to that binding—but testing's finding they're pretty cumbersome.

**Comment by MaxRev-Dev** [comment]
@twest820 https://github.com/OSGeo/gdal/milestones

**Comment by twest820** [comment]
Yes. Since there doesn't appear to be a tracking work item it's unclear when the missing C# read/write raster bindings will be added—nothing obviously relevant is linked in 3.8.4, 3.9.0, or 4.0 that I could see. Hence the question about the timing.

**Comment by MaxRev-Dev** [comment]
You need it - you add it. PRs are welcome and you can help to modify the interface.
https://github.com/OSGeo/gdal/pulls

Again. You're in the wrong place. This repo doesn't change the GDAL and there are [official bindings](https://www.nuget.org/packages/GDAL#readme-body-tab) that require GDAL installation on a target system.
Once GDAL is updated I can build corresponding bindings with native libraries here.

**Comment by twest820** [comment]
> You need it - you add it.

Thank you finally confirming this. We currently have exactly zero funding for work on GDAL and are already thoroughly underwater with other open source contributions. There's some hope things could change in few years, but that's entirely speculative at this point. (Also, quite frankly, we've often found large gaps between PRs welcome and actually getting changes into builds. Though every repo's community is different.)
