### ISSUE TITLE
GTIFF supported on the next release

### ISSUE THREAD

**Issue by vgallego** [MaxRev-Dev/gdal.netcore#113]
First of all, good job on your project, it is very convenient not to have to deal with native gdal, especially when using it in microservices that are created on demand, it is very useful for me not to have to depend on the installation and configuration of gdal to then use it, it is wonderful.

I am starting to work with Geotiff and when migrating my work using your library, I realize that it is not added to your project. Would this be possible for future revisions of your project? I ask this as I read another related thread on the subject: 

[link](https://github.com/MaxRev-Dev/gdal.netcore/issues/8)

Thanks in advance!

**Comment by MaxRev-Dev** [comment]
It's added by default and is being checked by CI for new builds.
Also, [from GDAL docs](https://gdal.org/drivers/raster/gtiff.html) - `This driver is built-in by default`.

https://github.com/MaxRev-Dev/gdal.netcore/blob/8984c59edfe245cc99dbd7fadf7c3de27ea54f80/tests/MaxRev.Gdal.Core.Tests.XUnit/CommonTests.cs#L112
