### ISSUE TITLE
Can't find default GDAL_DATA directory(3.6+)

### ISSUE THREAD

**Issue by allrelease** [MaxRev-Dev/gdal.netcore#115]
Hello, thank you very much for newer versions.

Default path of 'gdal-data' in ConfigureGdalData is $"runtimes/any-x64/native";
but files are located in "runtimes/any/native"(with downloaded nuget.org package)

I didn't check out OSGeo.GDAL building cmake scripts(as not a programmer...)

**Comment by MaxRev-Dev** [comment]
First of all, you're using the wrong packages. See [readme](https://github.com/MaxRev-Dev/gdal.netcore?tab=readme-ov-file#packages-nuget).
Secondly, I need help finding runtime information. Please use a bug issue template.

**Comment by MaxRev-Dev** [comment]
I won't review it until you provide the required information. Please, update your description.

**Comment by MaxRev-Dev** [comment]
If you come across the information that was requested, please don't hesitate to reopen the issue.
