### ISSUE TITLE
GML driver missing

### ISSUE THREAD

**Issue by JensKlambauer** [MaxRev-Dev/gdal.netcore#12]
**Describe the bug**
GML-Reader not work
System.ApplicationException: File C:\Temp\lakes.gml appears to be GML but the GML reader can't
be instantiated, likely because Xerces or Expat support was not configured in.
Missing dll- libs?

**To Reproduce**
Download GML-File Sample, http://qgis.org/downloads/data/qgis_sample_data.zip
``` 
        static void Main(string[] args)
        {
            MaxRev.Gdal.Core.GdalBase.ConfigureAll();
            System.Console.WriteLine($"IsConfigured = {MaxRev.Gdal.Core.GdalBase.IsConfigured}");

            var gmlDriver = Ogr.GetDriverByName("GML");
            var inDataSource = gmlDriver.Open("C:\\Temp\\lakes.gml", 0);
            var layer = inDataSource.GetLayerByIndex(0);
            System.Console.WriteLine($"Name - {layer.GetName()}");
        }
```
```
 <ItemGroup>
    <PackageReference Include="MaxRev.Gdal.Core" Version="3.0.1.25" />
    <PackageReference Include="MaxRev.Gdal.WindowsRuntime.Minimal" Version="3.0.1.35" />
  </ItemGroup>
```

**Environment information:**
- OS (version): Windows 10 (1909)
- Package version (core): 3.0.1.25
- Package version (runtime): 3.0.1.35

**Additional context**
I have not tested the linux runtime.
Sample-Code works with GDAL.Native 2.4.3 /.NETFramwork 4.7.2 https://www.nuget.org/packages/GDAL.Native/

**Comment by MaxRev-Dev** [comment]
That's not a bug - this is the way it [was configured](https://github.com/MaxRev-Dev/gdal.netcore/blob/master/configuregdal.sh#L49). Please, check out [this issue](https://github.com/MaxRev-Dev/gdal.netcore/issues/8#issuecomment-569864199).
Of course, [GML driver](https://gdal.org/drivers/vector/gml.html) is dependent on Xerces or libexpat. Again, this is [not a replacement for GDAL.Native](http://osgeo-org.1560.x6.nabble.com/gdal-dev-How-to-use-Gdal-c-bindings-with-NET-Core-td5389156.html), current package only provides a minimal bundle of drivers. But, you always can contribute to make it better.

**Comment by JensKlambauer** [comment]
OK, thanks for the answer.
