### ISSUE TITLE
Exception when referencing core 3.7.0 from 3.8.3.* runtime

### ISSUE THREAD

**Issue by CGSgeosite** [MaxRev-Dev/gdal.netcore#120]
when read ESRI-Shapefile:
========================
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by MaxRev-Dev** [comment]
Which runtime, which platform, which OS?

**Comment by CGSgeosite** [comment]
MaxRev.Gdal.WindowsRuntime.Minimal 3.8.3.286

**Comment by MaxRev-Dev** [comment]
First of all, it wasn't published when you tried last time. You have to ensure you use the latest package. Not the 3.7.0.x. The runner didn't complete that time, so you can try again.
Then the package you reference doesn't exist. The Core and Runtime were built separately in CI.

Run this line in CLI and rerun your app.
`dotnet add package MaxRev.Gdal.WindowsRuntime.Minimal`

The latest version (a single one) is `*.259`
https://www.nuget.org/packages/MaxRev.Gdal.WindowsRuntime.Minimal

**Comment by MaxRev-Dev** [comment]
I assume this one is resolved as [CI tests](https://github.com/MaxRev-Dev/gdal.netcore/actions/runs/7661511755) were completed successfully.

**Comment by CGSgeosite** [comment]
OS: Windows 10 
Visual studio 2022 
Runtime:
    <PackageReference Include="MaxRev.Gdal.Core" Version="3.8.3.286" />
    <PackageReference Include="MaxRev.Gdal.WindowsRuntime.Minimal" Version="3.8.3.259" />

**Comment by CGSgeosite** [comment]
OS: Windows 10 
Visual studio 2022 
Runtime:
   MaxRev.Gdal.Core Version="3.8.3.286" 
   MaxRev.Gdal.WindowsRuntime.Minimal Version="3.8.3.259"

**Comment by MaxRev-Dev** [comment]
So have you tried the latest runtime package?
As I already mentioned above - windows runtime was delayed in CI and was published around 12 hours ago. But your issue was created 18 hours ago which means you might reference a wrong runtime package.

And, of course, it would be nice to see `any code` here to repro this. Otherwise, I won't be able to investigate this and will close the issue.

**Comment by CGSgeosite** [comment]
The latest package is okay. Thanks
