### ISSUE TITLE
ReprojectImage Issues

### ISSUE THREAD

**Issue by junewai1993** [MaxRev-Dev/gdal.netcore#121]
Hi, I am trying to use the ReprojectImage to do the resampling of Tif Image to lower resolution. However, it is reported an error as following: 

- Unable to compute a transformation between pixel/line and georeferenced coordinates
- There is no affine transformation and no GCPs. 
- Specify transformation option DST_METHOD=NO_GEOTRANSFORM to bypass this check.

I tried to add an options to specify the transformation option, but it does not help, could any help to check how am i supposed to bypass the geotransform checking?

```
 string[] options2 = new string[] { "-to DST_METHOD=NO_GEOTRANSFORM" };
 Gdal.ReprojectImage(srcDs, dstDs, null, null, resamplingAlg, 0, 0, null, null, options2);
```

**Comment by MaxRev-Dev** [comment]
I'm not able to reproduce it. You can try to post a full [MRE](https://stackoverflow.com/help/minimal-reproducible-example) as a project (compress it and attach here).

One part that looks wrong to me, the parameters must be split on whitespace 
`{ "-to", "DST_METHOD=NO_GEOTRANSFORM" }`

**Comment by junewai1993** [comment]
Hi Max,

Thanks for your reply, yes, indeed the parameters has to be split on whitespace, I was not aware of this
