### ISSUE TITLE
GetProjectionRef vs GetReproject

### ISSUE THREAD

**Issue by junewai1993** [MaxRev-Dev/gdal.netcore#123]
Hi all, I am a trying to get the CRS from the geotiff, but I noticed that the string returned from _GetProjectionRef_ is slightly different from _GetProjection_. 

I am bit confused with the two  functions, and could not find a good documentation on these differences.

**Comment by MaxRev-Dev** [comment]
I believe it's an overload or an old binding name. The internal function is the same. 
https://github.com/OSGeo/gdal/blob/171e3361e9745bad15b4fe4719a3c3337d8eec8d/swig/include/Dataset.i#L308

Also from the docs, it should be **_equivalent_**
https://gdal.org/doxygen/classGDALDataset.html#ae6765f379a7ecf38b24c1ff5a06573a7
