### ISSUE TITLE
 Cannot find grib2_subcenter.csv after upgrade to 3.8.3

### ISSUE THREAD

**Issue by Mikiewitch** [MaxRev-Dev/gdal.netcore#128]
**Describe the bug**
The grib2_subcenter.csv is missing again after update to 3.8.3. This bug previously appeared after update to 3.6.1. We added the files manually last time as a workaround.

**To Reproduce**
Update to gdal version 3.8.3.

**Expected behavior**
Files should be present in the output.
`
**Environment information:**
 - OS (version): [e.g. Windows 10 (1903)]
 - Package version (core): [e.g. 3.8.3]
 - Package version (runtime): [e.g. 3.8.3]

**Comment by MaxRev-Dev** [comment]
So, it's not missing in latest packages. It should be copied to gdal-data from the main package.  See the package source: https://nuget.info/packages/MaxRev.Gdal.Core/3.8.3.286

But.

I see now, there's an issue with path to which GDAL_DATA option is being initialized during startup. 
I believe this should do the trick in the "most cases". I'll create a patch and mention specifics in the docs.

```csharp
Gdal.SetConfigOption("GDAL_DATA", Path.Combine(AppContext.BaseDirectory, "runtimes/any/native/gdal-data" ));
```

**Comment by Mikiewitch** [comment]
Thank you very much for a quick response. It helped.
