### ISSUE TITLE
Exception When Reading File GeoDatabase with Date Only Field

### ISSUE THREAD

**Issue by ceby-gannetflemming** [MaxRev-Dev/gdal.netcore#129]
Esri introduced the "Date Only" field with ArcGIS 3.2. When calling the GetFieldCount method of FeatureDefn on a file geodatabase that has a "Date Only" field, the following exception is thrown:
System.ApplicationException
  HResult=0x80131600
  Message=Error occurred in C:\utils\actions-runner\_work\gdal.netcore\gdal.netcore\build-win\gdal-source\ogr\ogrsf_frmts\openfilegdb\filegdbtable.cpp at line 900
  Source=MaxRev.Gdal.Core
  StackTrace:
   at OSGeo.OGR.FeatureDefn.GetFieldCount()

**Environment information:**
 - OS (version): Windows 10
 - Package version (core): 3.8.3.286

**Comment by MaxRev-Dev** [comment]
I won't be able to replicate this without additional information. I have only QGIS installed, as it's free to use. Is ArcGIS using GDAL internally - then which version specifically?
I didn't find any related changes in [geodatabase](https://github.com/OSGeo/gdal/commits/65e177b7e3277bc3f39d64ae44796a8c813f4129/ogr/ogrsf_frmts/filegdb) driver, nor in changelog.
Consider creating a MRE ([like here](https://github.com/MaxRev-Dev/gdal.netcore/issues/127#issue-2251821025)). Also, you can attach the file sample to your message.

**Comment by sirhcybe** [comment]
I've attached a file geodatabase with a Date Only attribute and a Time Only attribute that should replicate the issue.
[DateOnlyTest.gdb.zip](https://github.com/MaxRev-Dev/gdal.netcore/files/15238945/DateOnlyTest.gdb.zip)
ArcGIS does not use GDAL to my knowledge, but file geodatabases are a format that's proprietary to Esri so I expect that GDAL needs to play catchup to these new field types which were just released on November 7, 2023.
