### ISSUE TITLE
[BUG] CoordinateTransformation swaps axis

### ISSUE THREAD

**Issue by pergerch** [MaxRev-Dev/gdal.netcore#13]
**Describe the bug**
Using _CoordinateTransformation_ swaps the resulting coordinate axis.

**To Reproduce**
Look at this simple transformation from Web Mercator to WGS84:
[https://epsg.io/transform#s_srs=3857&t_srs=4326&x=1781111.8500000&y=6106854.8300000](https://epsg.io/transform#s_srs=3857&t_srs=4326&x=1781111.8500000&y=6106854.8300000)

This should result in the WGS84 (EPSG:4326) coordinate x=16, y=48.

```csharp
using System;
using MaxRev.Gdal.Core;
using CoordinateTransformation = OSGeo.OSR.CoordinateTransformation;
using SpatialReference = OSGeo.OSR.SpatialReference;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = 1781111.85;
            var y = 6106854.83;

            GdalBase.ConfigureAll();

            SpatialReference source = new SpatialReference(string.Empty);
            source.ImportFromEPSG(3857);
            SpatialReference destination = new SpatialReference(string.Empty);
            destination.ImportFromEPSG(4326);
            CoordinateTransformation transformer = new CoordinateTransformation(source, destination);

            double[] p = new double[3];

            transformer.TransformPoint(p, x, y, 0);

            Console.WriteLine($"Transformed {x}/{y} to {p[0]}/{p[1]}");

            // Output:
            // Transformed 1781111,85/6106854,83 to 47,9999999706363/15,999999975813965
        }
    }
}

```

**Expected behavior**
Passing X and Y coordinate should result in outputting X and Y coordinate and not swapping to Y and X.

**Environment information:**
 - OS (version): Windows 10 (1909)
 - Package version (core): 3.0.1.25
 - Package version (runtime): 3.0.1.35

**Additional context**
This is a simple demonstration. It is easy to just use p[1] and p[0] instead. But I believe that this is also the root cause for the method _Geometry.Transform(...)_ to swap the coordinates as well.

**Comment by pergerch** [comment]
I should maybe mention that this doesn't look like a GDAL 3.0 issue. In the console, GDAL transforms the coordinates correctly:

```bash
C:\>gdaltransform --version
GDAL 3.0.4, released 2020/01/28

C:\>gdaltransform -s_srs EPSG:3857 -t_srs EPSG:4326
1781111.85 6106854.83
15.999999975814 47.9999999706363 0
^C
C:\>
```

**Comment by MaxRev-Dev** [comment]
It's a GDAL 3.0 intended behavior, not a build engine bug.
Here's the original issue https://github.com/OSGeo/gdal/issues/1546 
Please, change the axis mapping strategy.
> srs_4326.SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER)
