### ISSUE TITLE
[BUG] Unable to load shared library 'gdal_wrap' or one of its dependencies

### ISSUE THREAD

**Issue by sokolik745** [MaxRev-Dev/gdal.netcore#132]
**Describe the bug**
A call GdalBase.ConfigureAll(); throws an exception when running on linux.

System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'gdal_wrap' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/LoadTest/GDAL/gdal_wrap.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/7.0.19/gdal_wrap.so: cannot open shared object file: No such file or directory
/LoadTest/GDAL/libgdal_wrap.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/7.0.19/libgdal_wrap.so: cannot open shared object file: No such file or directory
/LoadTest/GDAL/gdal_wrap: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/7.0.19/gdal_wrap: cannot open shared object file: No such file or directory
/LoadTest/GDAL/libgdal_wrap: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/7.0.19/libgdal_wrap: cannot open shared object file: No such file or directory

   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.AllRegister()
   at OSGeo.GDAL.Gdal.AllRegister()
   at MaxRev.Gdal.Core.GdalBase.ConfigureGdalDrivers(String gdalDataFolder)
   at MaxRev.Gdal.Core.GdalBase.ConfigureAll()
   at Program.<Main>$(String[] args) in C:\Git\mike-platform\Transfer\Common\ConsoleApp1\Program.cs:line 7

**To Reproduce**
- publish attached sample console application to linux-x64
- copy published folder to the WSL (Ubuntu 22.04)
- run dotnet ./GdalConfigureTest.dll
[GdalConfigureTest.zip](https://github.com/MaxRev-Dev/gdal.netcore/files/15499251/GdalConfigureTest.zip)

**Environment information:**
 - OS (version): Ubuntu 22.04 (WSL)
 - Package version (core): 3.8.3.286
 - Package version (runtime): 3.8.3.286

**Comment by emmetdelaney** [comment]
I am getting this same issue on a mac m1. When debugging the app it run's fine, however, when I `dotnet publish` and deploy to a lambda I am getting the same error as above.

**Comment by MaxRev-Dev** [comment]
@sokolik745 I don't see any issues with Ubuntu.
If you publish your app somewhere else, you must include the **runtimes** folder. Basically, archive **everything** that you have in **publish** directory.

<details><summary>Run log</summary>
<p>

<img width="748" alt="image" src="https://github.com/MaxRev-Dev/gdal.netcore/assets/24393967/c618036d-6980-42e8-9501-68fdbb64446e">



</p>
</details>

**Comment by MaxRev-Dev** [comment]
@emmetdelaney I suppose, you have the same issue. You must publish everything with the build output.
If you have any repros, feel free to attach here.
Also, consider that this sample from the OP doesn't contain MacosRuntime packages and to work it on Mac you need to add a corresponding package. 
If you deploy on Lamda, again you need to ship all the data. I can't confirm it works on AWS because I have only the [AzureFunction sample.](https://github.com/MaxRev-Dev/gdal.netcore/blob/e6e26d6bad7700adab267c92c3861475842d8951/tests/MaxRev.Gdal.Core.Tests.AzureFunctions/ConfigureFunction.cs#L13)

**Comment by sokolik745** [comment]
Maybe the problem is where the application is published. I can see that you published that right on the linux. But I and our pipeline is using windows machine to build and publish. And when I run this command on my local windows: 

` dotnet publish C:\Git\test\GdalConfigureTest\GdalConfigureTest\GdalConfigureTest.csproj -o C:\Git\test\GdalConfigureTest\GdalConfigureTest\bin\Publish -c Release --runtime linux-x64 --self-contained false`

then it generates publish folder without the runtimes folder and it looks like this: 
![image](https://github.com/MaxRev-Dev/gdal.netcore/assets/22426839/c18c6560-44bf-4f6f-b9c2-d86f81367190)

Everything in one folder and no runtimes folder in this case. What am I doing wrong?

**Comment by emmetdelaney** [comment]
> @emmetdelaney I suppose, you have the same issue. You must publish everything with the build output. If you have any repros, feel free to attach here. Also, consider that this sample from the OP doesn't contain MacosRuntime packages and to work it on Mac you need to add a corresponding package. If you deploy on Lamda, again you need to ship all the data. I can't confirm it works on AWS because I have only the [AzureFunction sample.](https://github.com/MaxRev-Dev/gdal.netcore/blob/e6e26d6bad7700adab267c92c3861475842d8951/tests/MaxRev.Gdal.Core.Tests.AzureFunctions/ConfigureFunction.cs#L13)

I can't share the repo I am working on unfortunately. In terms of copying the runtimes folder. I am assuming that when the package runs it will look for the runtime that corresponds with the current architecture of the host? For example if I deploy an aws lambda that is running on the `arm64` architecture. Gdal will looking at the runtimes folder and try and locate the `arm64` folder?

**Comment by MaxRev-Dev** [comment]
@sokolik745 If the app is **not** self-contained, it won't have the runtimes folder. However, the output should contain "lib***.so" (Linux dynamic libraries).
I tried publishing your app on Windows with `dotnet publish -c Release --runtime linux-x64 --self-contained false` and then run it in WSL. It worked the same.
Please make sure you have referenced the correct package (LinuxRuntime bundle or LinuxRuntime x64) as in this sample app.

<details><summary>Linux app publish directory</summary>
<p>

<img width="356" alt="image" src="https://github.com/MaxRev-Dev/gdal.netcore/assets/24393967/31fce9c2-75a2-4d35-ac37-fa441c981305">

</p>
</details>

**Comment by MaxRev-Dev** [comment]
@sokolik745 Regarding your initial post. I see that the stacktrace contains Windows path at the end (`$(String[] args) in C:\Git\mike-platform\..`). I assume that you tried to run this app on Windows. But you haven't referenced the Windows packages. And this was before publishing the app to WSL. 
If you run the same app on WSL you will have the different stacktrace (unix-like).

**Comment by emmetdelaney** [comment]
@MaxRev-Dev thanks for the help, switching to the LinuxRuntime package actually solved it for me. I was using the runtime identifier - `linux-arm64` in my `.csproj` file, therefore when I was running publish it was not copying over the runtimes folder. Adding this comment as it may help someone in the future. Can also confirm that the package works in aws lambda under the `arm64` architecture.

**Comment by MaxRev-Dev** [comment]
@sokolik745 I'm going to close this as we did not succeed with repro. Feel free to respond if you have any issues.
