### ISSUE TITLE
[BUG] SetAttributeFilter method converts strings to UTF8 byte array

### ISSUE THREAD

**Issue by ttruefix14** [MaxRev-Dev/gdal.netcore#135]
**Describe the bug**
SetAttributeFilter method converts strings to utf-8 byte array. As a result strings in other encodings dont work properly.

**To Reproduce**
Use SetAttributeFilter with any cyrillic symbols on MSSQL dataset with cyrillic collation.

**Expected behavior**
Create filter in source with proper encoding

**Environment information:**
 - OS (version): [e.g. Windows 11]
 - Package version (core): [e.g. 3.9.0.218]
 - Package version (runtime): [e.g. 3.9.0.218]

**Temporary Solution**
Invoke gdal function directly and pass string with proper encoding

```c#
OGR_L_SetAttributeFilter(Layer.getCPtr(inputLayer), filter);

[DllImport("gdal")]
static extern int OGR_L_SetAttributeFilter(HandleRef layer, [MarshalAs(UnmanagedType.LPStr)] string filter);
```

**Comment by MaxRev-Dev** [comment]
@ttruefix14 This library doesn't change or affect the SWIG interface in any way. Please, open a corresponding [issue](https://github.com/OSGeo/gdal/issues) in GDAL repository. Glad that you have a solution with P/Invoke. You can try to fix the bindings [here](https://github.com/OSGeo/gdal/blob/5481008668c818303c2b429b53860a2d787c189b/swig/include/ogr.i#L1309). Feel free to link this issue from an upcoming one.

**Comment by ttruefix14** [comment]
> @ttruefix14 This library doesn't change or affect the SWIG interface in any way. Please, open a corresponding [issue](https://github.com/OSGeo/gdal/issues) in GDAL repository. Glad that you have a solution with P/Invoke. You can try to fix the bindings [here](https://github.com/OSGeo/gdal/blob/5481008668c818303c2b429b53860a2d787c189b/swig/include/ogr.i#L1309). Feel free to link this issue from an upcoming one.

Thank you! Created issue in GDAL repo
