### ISSUE TITLE
Expose OGR_G_CreateGeometryFromEsriJson and OGR_G_CreateGeometryFromJson

### ISSUE THREAD

**Issue by OWiger** [MaxRev-Dev/gdal.netcore#152]
I'm working with ESRI ArcGIS Maps SDK, and as far as I can see, the only geometry format I can extract is esri json. 

Would it be possible to expose Geometry.CreateGeometryFromEsriJson() and Geometry.CreateGeometryFromJson() functions?

The function signatures are present in gdal.dll as OGR_G_CreateGeometryFromEsriJson and OGR_G_CreateGeometryFromJson

**Comment by MaxRev-Dev** [comment]
@OWiger This library doesn't change or affect the SWIG interface in any way. Please, open a corresponding [issue](https://github.com/OSGeo/gdal/issues) in GDAL repository. Feel free to link this issue from an upcoming one. The packages will be updated after GDAL release.

**Comment by OWiger** [comment]
> @OWiger This library doesn't change or affect the SWIG interface in any way. Please, open a corresponding [issue](https://github.com/OSGeo/gdal/issues) in GDAL repository. Feel free to link this issue from an upcoming one. The packages will be updated after GDAL release.

Ok, thanks!
