### ISSUE TITLE
[BUG] layer createfield - fielddefn Not supporting Chinese

### ISSUE THREAD

**Issue by gaoguoguang** [MaxRev-Dev/gdal.netcore#154]
layer createfield - fielddefn Not supporting Chinese

**Comment by MaxRev-Dev** [comment]
@gaoguoguang This library doesn't change or affect the SWIG interface in any way. Please, open a corresponding [issue](https://github.com/OSGeo/gdal/issues) in GDAL repository. Feel free to link this issue from an upcoming one. The packages will be updated after GDAL release.
