### ISSUE TITLE
Cannot run as Azure Function

### ISSUE THREAD

**Issue by bjornharrtell** [MaxRev-Dev/gdal.netcore#17]
I've done extensive attemps (also compiling my own nugets) but no matter what I do I seem to get the following error when attempting to run it as Azure Function.

The error is similar on both Windows and Linux consumption plans. Windows:

System.TypeInitializationException: The type initializer for 'GeoDk.Central.IO.GIS.DataSource' threw an exception. The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception. The type initializer for 'SWIGExceptionHelper' threw an exception. Unable to load DLL 'gdal_wrap' or one of its dependencies: The specified module could not be found. (0x8007007E) 

Linux:
System.TypeInitializationException: The type initializer for 'GeoDk.Central.IO.GIS.DataSource' threw an exception. The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception. The type initializer for 'SWIGExceptionHelper' threw an exception. Unable to load shared library 'gdal_wrap' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgdal_wrap: cannot open shared object file: No such file or directory 

Obviously it has problems finding the native dependencies, or a transitive dependency of them. Any ideas what might be causing this?

**Comment by bjornharrtell** [comment]
I've found out that the RID on Azure Function with Linux consumption plan is debian.10-x64, so I had my hopes up by building a package for that RID specifically. Unfortunately it did not help.

**Comment by MaxRev-Dev** [comment]
I'm not familiar with Azure Functions and also I haven't any subscriptions to check packages. But if you can debug it, it would be great.

To debug on windows, I use **dumbin** utility.
Linux is much easier: `export LD_DEBUG=files`

Also, I want to notice that the "right" [RID is linux-64](https://github.com/MaxRev-Dev/gdal.netcore/blob/14cf55dc44cff1a94abb1d5677b92c0da3d8709f/GNUmakefile#L58), as it stays for "any" unix runtime in package content delivery.

Currently, I'm working on 3.1.x release and already adjusted some build scripts. One more thing to be done is configuring windows nmake patches in **win/presource** folder.

**Comment by bjornharrtell** [comment]
I've been able to get it to work. Apparently there are some rather strange quirks when dealing with native dependencies and Azure Functions. See https://github.com/Azure/Azure-Functions/issues/622 for more details.

**Comment by KirkDybvik** [comment]
@bjornharrtell  - I am glad to hear you got this to work. I am facing this issue now.  Looking at https://github.com/Azure/Azure-Functions/issues/622 there are a few things mentioned about PostBuldEvent and AfterPublish.   Which way did you use?   I may explore both to try to figure it out. Any suggestions from someone with experience with this issue would be welcome.

**Comment by bjornharrtell** [comment]
Might not remember all details but this is what I think made it work for me:

```xml
<Target Name="PostPublish" AfterTargets="AfterPublish">
  <Exec Command="mv $(PublishDir)bin/runtimes/linux-x64/native/* $(PublishDir)bin/" />
</Target>
```

Since I use mv directly it's *nix only I suppose.

**Comment by KirkDybvik** [comment]
After some fiddling around, I was able to get my Azure function using MaxRev nuget packages to work on linux.  This is what I did from my Win10 VS2022 machine.   There are likely other/better ways, am just happy to get something that works!   If anyone sees problems with this or has comments, please post them.

I include a link to the Microsoft doc for doing recursive directory copy.



    <Target Name="CopyFilesAfterBuild" AfterTargets="PostBuildEvent">
	    <ItemGroup>
		    
		    <MySourceFiles Include="$(TargetDir)runtimes\linux-x64\**\*.*"/>
	    </ItemGroup>
		<Copy SourceFiles="@(MySourceFiles)" DestinationFolder="$(PublishDir)\bin\%(RecursiveDir)%(Filename)%(Extension)" />
	</Target>

**Comment by KirkDybvik** [comment]
Looks like the formatting got messed up on the link to the MS doc, here is another try
[https://docs.microsoft.com/en-us/visualstudio/msbuild/copy-task?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSBuild.Copy.SourceFileNotFound)%26rd%3Dtrue&view=vs-2022](url)
