### ISSUE TITLE
Not possible to load drivers on CentOS 7

### ISSUE THREAD

**Issue by xd2020** [MaxRev-Dev/gdal.netcore#175]
My program references these three packages MaxRev.Gdal.Core MaxRev.Gdal.LinuxRuntime.Minimal MaxRev.Gdal.WindowsRuntime.Minimal. There is no problem in the windows environment, but an error is prompted in the linux environment. I checked the output file and there is indeed no problem. For those files that reported errors, my linux system is contos 7.6

I have tried the same problem in debug or release mode

Please help tell me how to solve this problem

**Describe the bug**
Unhandled exception. System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'gdal_wrap' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/xd/testTile/runtimes/any/native/gdal-data/gdal_wrap.so: cannot open shared object file: No such file or directory
/xd/testTile/runtimes/linux-x64/native/gdal_wrap.so: cannot open shared object file: No such file or directory
/xd/testTile/runtimes/linux-x64/native/maxrev.gdal.core.libshared/gdal_wrap.so: cannot open shared object file: No such file or directory
/root/dotnet/shared/Microsoft.NETCore.App/8.0.6/gdal_wrap.so: cannot open shared object file: No such file or directory
/xd/testTile/gdal_wrap.so: cannot open shared object file: No such file or directory
/xd/testTile/runtimes/any/native/gdal-data/libgdal_wrap.so: cannot open shared object file: No such file or directory
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /xd/testTile/runtimes/linux-x64/native/libgdal.so.36)
/xd/testTile/runtimes/linux-x64/native/maxrev.gdal.core.libshared/libgdal_wrap.so: cannot open shared object file: No such file or directory
/root/dotnet/shared/Microsoft.NETCore.App/8.0.6/libgdal_wrap.so: cannot open shared object file: No such file or directory
/xd/testTile/libgdal_wrap.so: cannot open shared object file: No such file or directory
/xd/testTile/runtimes/any/native/gdal-data/gdal_wrap: cannot open shared object file: No such file or directory
/xd/testTile/runtimes/linux-x64/native/gdal_wrap: cannot open shared object file: No such file or directory
/xd/testTile/runtimes/linux-x64/native/maxrev.gdal.core.libshared/gdal_wrap: cannot open shared object file: No such file or directory
/root/dotnet/shared/Microsoft.NETCore.App/8.0.6/gdal_wrap: cannot open shared object file: No such file or directory
/xd/testTile/gdal_wrap: cannot open shared object file: No such file or directory
/xd/testTile/runtimes/any/native/gdal-data/libgdal_wrap: cannot open shared object file: No such file or directory
/xd/testTile/runtimes/linux-x64/native/libgdal_wrap: cannot open shared object file: No such file or directory
/xd/testTile/runtimes/linux-x64/native/maxrev.gdal.core.libshared/libgdal_wrap: cannot open shared object file: No such file or directory
/root/dotnet/shared/Microsoft.NETCore.App/8.0.6/libgdal_wrap: cannot open shared object file: No such file or directory
/xd/testTile/libgdal_wrap: cannot open shared object file: No such file or directory

   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.GDAL.GdalPINVOKE.AllRegister()
   at OSGeo.GDAL.Gdal.AllRegister()
   at MaxRev.Gdal.Core.GdalBase.ConfigureGdalDrivers(String gdalDataFolder)

 
![image](https://github.com/user-attachments/assets/38dd5c77-e5c3-4584-8d6c-72d8a6e41897)

**Environment information:**
 - OS (version): [e.g. linux  (contos 7.6)]
 - Package version (core): [.NET 8]
 - Package version (runtime): [3.10.0.306]

**Comment by xd2020** [comment]
I added this code during initialization

            if (OperatingSystem.IsLinux())
            {
                GdalBase.EnableRuntimeValidation = false;
                GdalBase.ConfigureGdalDrivers();
                //Proj.Configure("/usr/local/share/proj/");
            }
            else
            {
                GdalBase.ConfigureAll();
            }

**Comment by MaxRev-Dev** [comment]
I believe you have a typo in the distro naming. If you're referring to CentOS 7, then you missed [this part of the readme](https://github.com/MaxRev-Dev/gdal.netcore?tab=readme-ov-file#q-packages-does-not-work-on-centos-7-ubuntu-1804).

CentOS 7 has reached EOL (end-of-life) and is not supported now.

The supported distros are anything that is based on **glibc 2.31+**

**Comment by xd2020** [comment]
I installed GDAL but still don't have these files. Please tell me what else needs to be done
  
gdal-csharp.dll, gdalconst_csharp.dll, ogr_csharp.dll, and osr_csharp.dll 
 

I don't understand where to get these files

/root/dotnet/linux-x64/gdal_wrap.so: cannot open shared object file: No such file or directory
libgdal.so.34: cannot open shared object file: No such file or directory
libgdal_wrap.so: cannot open shared object file: No such file or directory
/root/dotnet/linux-x64/gdal_wrap: cannot open shared object file: No such file or directory
/root/dotnet/linux-x64/libgdal_wrap: cannot open shared object file: No such file or directory

**Comment by xd2020** [comment]
I installed GDAL but still don't have these files. Please tell me what else needs to be done
  
gdal-csharp.dll, gdalconst_csharp.dll, ogr_csharp.dll, and osr_csharp.dll 
 

I don't understand where to get these files

/root/dotnet/linux-x64/gdal_wrap.so: cannot open shared object file: No such file or directory
libgdal.so.34: cannot open shared object file: No such file or directory
libgdal_wrap.so: cannot open shared object file: No such file or directory
/root/dotnet/linux-x64/gdal_wrap: cannot open shared object file: No such file or directory
/root/dotnet/linux-x64/libgdal_wrap: cannot open shared object file: No such file or directory

**Comment by xd2020** [comment]
I installed GDAL but still don't have these files. Please tell me what else needs to be done
  
gdal-csharp.dll, gdalconst_csharp.dll, ogr_csharp.dll, and osr_csharp.dll 
 

I don't understand where to get these files

/root/dotnet/linux-x64/gdal_wrap.so: cannot open shared object file: No such file or directory
libgdal.so.34: cannot open shared object file: No such file or directory
libgdal_wrap.so: cannot open shared object file: No such file or directory
/root/dotnet/linux-x64/gdal_wrap: cannot open shared object file: No such file or directory
/root/dotnet/linux-x64/libgdal_wrap: cannot open shared object file: No such file or directory

**Comment by MaxRev-Dev** [comment]
@xd2020 Again, if you don't understand how the library is packaged, I recommend to dockerize your application or move to a newer LTS/STS distro.

You don't need to compile bindings if you reference `MaxRev.Gdal.Core` as it already contains all dynamic libraries.

You only need to install the same version of GDAL and bindings. There are two ingredients:
- The bindings are coming from`MaxRev.Gdal.Core` or [you can also build your own bindings](https://gdal.org/en/stable/api/csharp/csharp_compile_cmake.html#csharp-compile-cmake). The latter one requires direct reference of above-mentioned DLLs.
- Then you have binaries and drivers - that's your GDAL installation.

Once you set everything, you have to disable runtime validation. By default, Core package expects one of the Runtime* nuget packages to be installed. This can be done by setting the following flag - `GdalBase.EnableRuntimeValidation = false;`
