### ISSUE TITLE
[BUG] Unable to call SpatialReference.SetWellKnownGeogCS

### ISSUE THREAD

**Issue by pictureaday** [MaxRev-Dev/gdal.netcore#2]
(I suspect I'm missing a call that will include the DLLs that are necessary)
**Describe the bug**
Windows 10, VS 2019, Nuget packages. 
After constructing a SpacialReference object I try to call SetWellKnownGeogCS, and receive the error: "System.EntryPointNotFoundException: 'Unable to find an entry point named '?' in DLL 'osr_wrap'.'

**To Reproduce**
In a console based application netcore v2.2:
GdalBase.ConfigureAll();
Gdal.AllRegister();

// Uncomment line below to get a different EntryPoint exception
//Console.WriteLine("Osr.Version: {0}.{1}", Osr.GetPROJVersionMajor(), Osr.GetPROJVersionMinor());

IntPtr intPtr = new IntPtr();
SpatialReference spatialReference = new SpatialReference(intPtr, true, null);
spatialReference.SetWellKnownGeogCS("WGS84");

**Expected behavior**
The above should run without error/exception.

**Environment information:**
 - OS (version): Windows 10
 - Package version (core): v3.0.0.4
 - Package version (runtime): v3.0.0.4
 - Visual Studio Version: 2019 (v16.1.0)

**Additional context**
I have not yet tested this on linux.

**Comment by MaxRev-Dev** [comment]
I had a repro on my machine. That must be a broken reference in library, caused by a version collision during the build. 
Already building a new version for both runtimes.

**Comment by pictureaday** [comment]
> I had a repro on my machine. That must be a broken reference in library, caused by a version collision during the build.
> Already building a new version for both runtimes.

Do you know when you might be able to post the new packages?

Thanks!

**Comment by MaxRev-Dev** [comment]
> Do you know when you might be able to post the new packages?

Sorry for late reply. On a free time I'm trying to complete the build. 
Currently I'm experiencing problems with **geotiff** library in windows build.
I could release it without geotiff, but by default it was and stays in linux package.
It would be nice, if you could help.

**Comment by pictureaday** [comment]
Believe me I'm trying to help. The build process is very complicated and we are hitting quite a few hiccups. Still learning how to link everything up on the windows side before moving on to the linux side.

**Comment by MaxRev-Dev** [comment]
Almost completed the build with 3.0.1 using an internal geotiff lib for windows. Need a few days to test it. 
Also, I've found how to create a **SpatialReference**. So, spatial ref in for **OGR** namespace is not working. This comes from a swig interface bindings directly from gdal. 
But you can use **OSR** instead. 
![image](https://user-images.githubusercontent.com/24393967/66434986-70984a00-ea2c-11e9-924e-afbbc6a0a1f8.png)

**Comment by MaxRev-Dev** [comment]
Please, checkout a new 3.0.1.2 release [MaxRev.Gdal.Core](https://www.nuget.org/packages/MaxRev.Gdal.Core/). And tell me, if you have any issues with it.

**Comment by pictureaday** [comment]
Thanks. I'm using SpatialReference from OSR as you suggested and it works. I'm also using the new packages. Thanks for the effort!
