### ISSUE TITLE
Native binaries collision with libgdiplus

### ISSUE THREAD

**Issue by tyaleze** [MaxRev-Dev/gdal.netcore#21]
I got the following error when i try to use the library. I have zlib 1.2.11 (latest version) and its dev version installed but i am still getting the same error.

I get success if i use Gdal.Core package and its runtimes. but their version are old.

The detail i got from LD_DEBUG below :

  23172:	checking for version `GLIBC_2.4' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /usr/lib/x86_64-linux-gnu/libgif.so.7 [0]
     23172:	checking for version `GLIBC_2.2.5' in file /lib/x86_64-linux-gnu/libc.so.6 [0] required by file /usr/lib/x86_64-linux-gnu/libgif.so.7 [0]
     23172:	checking for version `GLIBC_2.2.5' in file /lib/x86_64-linux-gnu/libm.so.6 [0] required by file /usr/lib/x86_64-linux-gnu/libpng16.so.16 [0]
     23172:	checking for version `ZLIB_1.2.9' in file /home/tyaleze/Desktop/code/server/teoframework/TeoGIS.Framework/TeoFramework/bin/Debug/netcoreapp3.1/runtimes/linux-x64/native/libz.so.1 [0] required by file /usr/lib/x86_64-linux-gnu/libpng16.so.16 [0]
     23172:	/home/tyaleze/Desktop/code/server/teoframework/TeoGIS.Framework/TeoFramework/bin/Debug/netcoreapp3.1/runtimes/linux-x64/native/libz.so.1: error: version lookup error: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16) (fatal)
     23172:	
     23172:	file=/usr/lib/x86_64-linux-gnu/liblibgdiplus.so [0];  destroying link map
     23172:	
     23172:	file=/usr/lib/x86_64-linux-gnu/libcairo.so.2 [0];  destroying link map
     23172:	
     23172:	file=/usr/lib/x86_64-linux-gnu/libtiff.so.5 [0];  destroying link map

**Environment information:**
 - OS Ubuntu 18.04 TLS
 - Package 3.0.1.100
Dotnet Core 3.1

**Comment by MaxRev-Dev** [comment]
These packages compiled under and targeting only **linux-x64**. 
Libraries are copied on build from /runtimes/linux-x64/native to output directory.
Are you running on **64-bit** machine?
If not - dependencies from the package wont be available on runtime.

Unix packages have their own **libz** (configured as internal driver) and **libc**. 
Just tested them locally in **WSL x64** (Ubuntu 18.04). They are stable.


<details>
  <summary>Screenshots</summary> 

![image](https://user-images.githubusercontent.com/24393967/87308295-b1754000-c523-11ea-895e-620f88c87f6f.png)
![image](https://user-images.githubusercontent.com/24393967/87309070-c43c4480-c524-11ea-9523-88e0b222fa20.png)

</details>

**Comment by tyaleze** [comment]
My system is indeed x64

**Comment by tyaleze** [comment]
[asp.zip](https://github.com/MaxRev-Dev/gdal.netcore/files/4917837/asp.zip)

This is a sample app. I got error after creating bitmap.

**Comment by MaxRev-Dev** [comment]
1. You are calling native GDAL methods without configuring drivers paths. This library has a wrapper-bootstrapper to configure GDAL's startup. See [how to use](https://github.com/MaxRev-Dev/gdal.netcore#how-to-use).
2. You should call them once at startup as registration is expensive operation and objects are static singletons.
For me libraries are loading successfully after applying changes. 

Also, I want to notice that using bitmap in asp.net core is not a good idea, as it has a windows dependency (Microsoft.Win32.SystemEvents). And it also requires libc6-dev and libgdiplus libraries. 
Consider to use [ImageSharp](https://github.com/SixLabors/ImageSharp)

**Comment by tyaleze** [comment]
Yes i know using bitmap is risky but i am porting a huge library to .net core so i should make it work. 

I could not make it work. Could you please send me a working sample project?

Thanks.

**Comment by MaxRev-Dev** [comment]
@tyaleze Working sample - [asp.zip](https://github.com/MaxRev-Dev/gdal.netcore/files/4920008/asp.zip)

**Comment by tyaleze** [comment]
Sorry but i am still getting the error when i try to create Bitmap

**Comment by MaxRev-Dev** [comment]
@tyaleze GDAL is not dependent on Bitmap and vise versa

**Comment by tyaleze** [comment]
I know but when i remove the packages it works. If only i add the packages it fails. I tried to use GDAL.Net.Core library and its runtimes it also works.

**Comment by MaxRev-Dev** [comment]
Then this issue is similar to #9. 
In my opinion, It fails because **libgdiplus** uses **libpng16** from system libraries and loads it on startup before gdal.
Currently, I can't find any solution to fix this. Maybe its worth to compile all to separate directory like runtimes/linux-x64/native/**gdal**.    

> /home/tyaleze/Desktop/code/server/teoframework/TeoGIS.Framework/TeoFramework/bin/Debug/netcoreapp3.1/runtimes/linux-x64/native/libz.so.1: error: version lookup error: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16) (fatal)

23172:
23172: file=/usr/lib/x86_64-linux-gnu/liblibgdiplus.so [0]; destroying link map

**Comment by tyaleze** [comment]
Thanks for your help. I am using gdal for dynmic tiling. i crop images from big images on  runtime. so i understand that if i use ImageSharp or any other cross platform library for creating images, this problem will be solved. right?

**Comment by MaxRev-Dev** [comment]
@tyaleze sorry for late reply. That should be fixed by ImageSharp, because it does not have any binary dependency - it's fully managed.

**Comment by MaxRev-Dev** [comment]
> [asp.zip](https://github.com/MaxRev-Dev/gdal.netcore/files/4917837/asp.zip)
> 
> This is a sample app. I got error after creating bitmap.

@tyaleze I've tested your pinned project with packages v3.1.2.100. Everything looks fine.

**Comment by tyaleze** [comment]
Thanks. i took your advise and change all System.Drawing object into ImageSharp. Everything works fine.

**Comment by MaxRev-Dev** [comment]
@tyaleze One more remark. 
I looked through the logs, and there was no collisions with dependencies.
Again, as far as I know our GDAL drivers does not use `libgdiplus`.
You must install libgdiplus in your environment.
Ubuntu: `apt-get install -y libgdiplus`
CentOS: `yum install -y libgdiplus`
