### ISSUE TITLE
[BUG] System.TypeInitializationException : The type initializer for 'OSGeo.OGR.OgrPINVOKE' threw an exception. While unit testing with xUnit

### ISSUE THREAD

**Issue by ripp80** [MaxRev-Dev/gdal.netcore#22]
**Describe the bug**
I have problems with initializiting Gdal while using xUnit. `GdalBase.ConfigureAll();` was called.

```
  Message: 
    System.TypeInitializationException : The type initializer for 'OSGeo.OGR.OgrPINVOKE' threw an exception.
    ---- System.TypeInitializationException : The type initializer for 'SWIGExceptionHelper' threw an exception.
    -------- System.DllNotFoundException : Unable to load DLL 'ogr_wrap' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Stack Trace: 
    OgrPINVOKE.GetDriverByName(String jarg1)
    Ogr.GetDriverByName(String name)
```

**Environment information:**
 - OS (version): [e.g. Windows 10 (2004)]
 - Package version: 3.0.1.2 (same with he 3.1.100)

**Comment by MaxRev-Dev** [comment]
Please, checkout the test project. 
And consider, you won't be able to run them on 32-bit architecture. 
Currently, these packages targeting 64-bit systems only.

**Comment by ripp80** [comment]
Great! All those info helps. Now it works. Before I had AnyCPU enabled and tests were runned in x86.
