### ISSUE TITLE
Native dependencies bugs

### ISSUE THREAD

**Issue by Gigas002** [MaxRev-Dev/gdal.netcore#23]
## Problem

While using prebuilt gdal from [gisinternals](https://www.gisinternals.com/development.php) (and [nuget packages](https://www.nuget.org/packages/GDAL/) by @szekerest), I've noticed some issues, which I've explained in details in gdal repo:

- Using wildcard breaks gdalbuildvrt [osgeo/gdal - issue1749](https://github.com/OSGeo/gdal/issues/1749)
- Bad support for cyrillic paths [osgeo/gdal - issue 1245](https://github.com/OSGeo/gdal/issues/1245)

These issues also appears in this library. Recently I've located a new problem, related to this nuget package: my antivirus deletes the package instantly because of `libgeos_c.dll`.

## Solution

Not so long ago I've found some time to sort out how gdal builds and managed to find a solution for these issues.

First two I are fixed by changing gdal's `nmake.opt`. It requires a new dependency -- iconv (I've got it through vcpkg) and adding those paths to `nmake.opt`:

```txt
LIBICONV_INCLUDE = -IC:\vcpkg\installed\x64-windows\include
LIBICONV_LIBRARY = C:\vcpkg\installed\x64-windows\lib\libiconv.lib
LIBICONV_CFLAGS = -DICONV_CONST=const
```

I've also specified `wsetargv.obj` in `nmake.opt`, so it can be a part of solution too:

```txt
SETARGV = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\lib\x64\wsetargv.obj"
```

I've tested the fixes above on latest gdal 3.1.2 with PROJ 7.1.0 (installed it's deps through vcpkg, built with cmake+vs using sqlite3 and libtiff) built on win-x64. Even though I've tested it on gdal apps, not the library, I think that might be also a solution for resolving the same issue in library.

Regarding the geos issue, I've tried to build geos with your `win/getgeos.bat` script, but antivirus still deleted the `libgeos_c.dll`. Building the newer commit (e.g. [3.8.1 release](https://github.com/libgeos/geos/commit/24650422b3982f17cc493fe92a70228f2ad624b4), not 3.8.0) fixes the issue. I suppose there were some kind of vulnerability in 3.8.0, idk.

I'm not sure how your binaries are built and don't want to break anything, so I've decided to open an issue instead of PR to convey this information to you.

**Comment by Gigas002** [comment]
I would also like to add a new dependency-related problem:
`SpatialReference.ExportToPROJJSON(out string)` method throws an exception, saying that it requires PROJ 6.2 or higher. I've tried building PROJ 7.1 and it seems the same as current version, so I propose to use the latest version.

**Comment by MaxRev-Dev** [comment]
@Gigas002 Thanks for this investigation. 

This build system is very simple and not stable (there are no CI build tests).
 - fetching sources (on windows this is done by one of `get{component}.bat` files.
 - building them - is the second part of batch files.

Next steps, in my opinion, is to union configuration variables from `GdalCore.opt` and `CONFIGVARS.vat` and then rewrite windows part to nmake/cmake. 

**Issue review:**
1. Good find - wildcards and cyrillic paths.
2. About antivirus - can't repro that, win10 standard windows defender with latest update did not find any threats.  
2. We can export `SETARGV` variable to `CONFIGVARS.bat`, but it should be checked for path before build or set a relative path to `vcvarsall64.bat`.

There are several ways we can add **libiconv** library to build pipeline. 
- create a batch script and fetch sources from git and then compile them (pros: original sources, cons: **maybe 7z needed**).
- provide a compiled sources (there can be some license compliance issues, but we already use swig, tcl, vc++ binaries with no license review). 
- add **vcpkg** - this is a new dependency and maybe only for this library. It does not provide all libraries we need and also the fresh versions of other libraries like **PROJ,GEOS, etc** are not available.   

Binaries that we can use (with 7z as another dep): 
https://github.com/pffang/libiconv-for-Windows/tree/v1.16

**Comment by Gigas002** [comment]
Last time, when I've build Gdal (ver. 3.1.2), I've used the vcpkg. As you know, the PROJ and Gdal itself out there is pretty outdated. So I've pulled the PROJ dependencies (minimal, `vcpkg install sqlite3:x64-windows tiff:x64-windows`) and then built PROJ 7.1.0 from source (full [guide](https://proj.org/install.html)), using this cmake and VS2019 (16.6.5 to be more precise).
I've took libiconv for gdal from vcpkg too (`vcpkg install libiconv:x64-windows`). The Gdal seems to built and work fine after this.

I also think, that gdal's port on vcpkg will be updated in the upcoming release, look at [this](https://github.com/microsoft/vcpkg/issues/11905) issue and a linked [PR](https://github.com/microsoft/vcpkg/pull/9100) (they're also switching the build methods in this PR, so that might be interesting/useful). Don't know much details, but probably if they'll be able to build 3.1.x Gdal that means, that they're updating all dependencies for it too? Anyway, we can request ports adding/updating on vcpkg repo (I've done it for [PROJ 7.1.0](https://github.com/microsoft/vcpkg/issues/12449) and someone's already grabbed the thing).

So I suppose that would be a good idea to pull all the needed dependencies by vcpkg, since it's also very easy to build and use (and easier to automate, I suppose), but we might need to wait until the ports will be added/updated. For now we could list all the needed dependencies and check their versions/availability on vcpkg.

Regarding the antivirus issue, I was using Kaspersky antivirus, when it deleted the libgeos_c.dll. I've tried to build geos from source with cmake/vs, but lib from 3.8.0 build is still deleted by antivirus (so it's not current repo's problem obviously). Guess we can safely update it to the latest stable release, since it doesn't break anything. (BTW, it seems, like geos will be updated in [vcpkg ](https://github.com/microsoft/vcpkg/pull/12163) soon too)

**Comment by MaxRev-Dev** [comment]
Several months ago, I had some experience with vcpkg. 
Of course, we can use vcpkg as package manager for pulling **outdated** libraries.
But what about new releases in vcpkg - that not worth it . Your issue for PROJ 7.1.0 is open for 24 days with no updates. The same is for GDAL 3.1 - they are moving, but that thread is too buggy on unix.

And more one thing, I'm using concrete versions of main libraries. With vcpkg we can't specify them directly in builds.
https://github.com/MaxRev-Dev/gdal.netcore/blob/70ab3da2153f8b0679f29092ed358de6de120297/win/CONFIGVARS.bat#L5-L12
 
I'm not against using vpckg. Furthermore, integration will bring us more drivers and a bit of automation for windows build pipeline. 

Let's establish a list of packages that we can pull using vcpkg:
- curl
- sqlite3
- tiff
- geotiff 
- jpeg
- png
- iconv 
- zlib
- hdf5

Other libraries optional:
- hdf4 [**missing**]
- hdfs [available, new for us]
- mongo-cxx-driver[boost] [new] 
- netcdf-c [new]
- xerces [new]
- expat [new]
- kml [new]

**Comment by Gigas002** [comment]
Good point about versioning. Judging by [vcpkg's roadmap](https://github.com/microsoft/vcpkg/wiki/Roadmap), they're planning to support specifiying versions explicitly (yet it was planned for june release and still not released). It would be great if they'll complete this roadmap since it contains nice features. Gdal itself doesn't release that frequently, so I guess using slightly outdated packages between releases is fine.
I also browsed their release history, and it seems like they're trying to release a new version each month, but this year has gone wrong. Even if it's not, well, very good for now, I think that it'll be a great thing in the future.
I'll take a look at the packages latest versions vs vcpkg available versions and add an issues to their repository. At least with that I can help.

**Comment by MaxRev-Dev** [comment]
@Gigas002 The work is in progress.
Finally, I rewrote a windows part to **nmake** (almost all batch files).
I did compiled GDAL for both runtimes, but have not yet adjusted **docs** and makefiles for gathering binaries.

About VCPKG integration with GDAL:
That was a big problem to [configure right](https://github.com/OSGeo/gdal/issues/2053#issuecomment-673330657) both PROJ and GDAL - I've spent a half of a week for this. 

Just a moment with configuring PROJ was insane:
https://github.com/MaxRev-Dev/gdal.netcore/blob/bff4708f48cffa3882f583d153e47b5a939d99eb/unix/gdal-makefile#L56-L70
Configure also for GDAL ignores custom curl, sqlite3, hdf5:
https://github.com/MaxRev-Dev/gdal.netcore/blob/bff4708f48cffa3882f583d153e47b5a939d99eb/unix/configuregdal.sh#L23-L29

**Comment by Gigas002** [comment]
Well done!
In the meanwhile, I've checked the versions in the vcpkg from the latest master branch build (and also attached the links to the repos to easily check for versions):

curl -- 7.71.1 ([latest](https://github.com/curl/curl))
sqlite3 -- 3.32.3 ([3.33.0 released](https://www.sqlite.org/download.html))
libtiff -- 4.1.0 ([latest](https://gitlab.com/libtiff/libtiff))
libgeotiff -- 1.4.2-10 ([1.6.0 released](https://github.com/OSGeo/libgeotiff))
libjpeg-turbo -- 2.0.4 ([2.0.5 released](https://github.com/libjpeg-turbo/libjpeg-turbo))
libpng -- 1.6.37 ([latest](http://www.libpng.org/pub/png/libpng.html))
libiconv -- 1.16 ([latest](https://www.gnu.org/software/libiconv/))
zlib -- 1.2.11 ([latest](https://zlib.net/))
hdf5 -- 1.12.0 ([latest](https://www.hdfgroup.org/downloads/hdf5))
libhdfs -- 2019-11-05 (not sure if I located the right library, but I suppose it's outdated, [3.3.0 released on 14.07.2020](https://hadoop.apache.org/releases.html))
mongo-cxx-driver -- 3.4.0-5 ([3.6.0 released](https://github.com/mongodb/mongo-cxx-driver/))
netcdf-c -- 4.7.3 ([4.7.4 released](https://github.com/Unidata/netcdf-c))
xerces-c -- 3.2.3 ([latest](https://github.com/apache/xerces-c))
expat -- 2.2.7 ([2.2.9 released](https://github.com/libexpat/libexpat))
libkml -- 1.3.0-4 ([latest?](https://github.com/libkml/libkml))
proj4 -- 6.3.1 ([7.1.0 released](https://github.com/OSGeo/PROJ))
geos -- 3.6.4 ([3.8.1 released](https://github.com/libgeos/geos))

Missing:

hdf4 -- [4.2.15](https://support.hdfgroup.org/ftp/HDF/releases/)

**Comment by MaxRev-Dev** [comment]
@Gigas002 Good news. After a long break, I'm continuing to implement this feature.
We have already a working windows build and tests are passing!

But currently there is a problem with building `PROJ` on linux.  
All previous configurations were using a system `curl` library, and I want to link `gdal` against a version built by `vcpkg`. 
There is a missing `curl-config` on linux in vcpkg, so I don't know how to make it work.
How it's going - we have an open issue for now: https://github.com/microsoft/vcpkg/issues/14459

**Comment by Gigas002** [comment]
Awesome!
Not related to this, but I also think, that we can remove **out of support** dotnet versons targets (`netcoreapp2.2` and `netcoreapp3.0`)? My guess we should target only LTS releases (2.2, 3.1, upcoming 5.1).

**Comment by MaxRev-Dev** [comment]
> My guess we should target only LTS releases (2.2, 3.1, upcoming 5.1).

Yes, that's a good point about targets. Sure it will be **LTS** (2.2,3.1) and **current** (5.0). But what about **netstandard2.1** for libraries? It's [not deprecated](https://docs.microsoft.com/ru-ru/dotnet/standard/net-standard#net-standard-not-deprecated) and maybe some libraries would use it.

**Comment by Gigas002** [comment]
Yes, I suppose it's better to pack netstandard builds at least for a near future.
