### ISSUE TITLE
proj.db location from nuget

### ISSUE THREAD

**Issue by CropRecords** [MaxRev-Dev/gdal.netcore#25]
Hi,

This is in case it helps anyone else, though I do have a question further below.

When running the 3.0.1.25 version of MaxRev.Gdal.Core I notice that when I need to load something I was getting a error:

System.ApplicationException: 'PROJ: proj_create_from_database: Cannot find proj.db'

Looking into the debug folder, I notice that 
{project}\bin\Debug\netcoreapp3.0 contains proj.db but
{project>\bin\Debug\netcoreapp3.0\maxrev.gdal.core.libshared is empty.

Copying proj.db into {project>\bin\Debug\netcoreapp3.0\maxrev.gdal.core.libshared fixes the issue.

I was not successful in changing environment variables to locate this file for some reason:
`SystemEnvironment.AddEnvironmentVariable("PROJ_LIB", @"C:\tmp");`
for example, does not work.

For the new version of MaxRev.Gdal.Core, 3.1.0.100 released on nuget, it is for .NetStandard 2.1, not 2.0. Can anyone comment on why this is the case? I need to stick with 2.0 for other reasons.

**Comment by MaxRev-Dev** [comment]
@CropRecords hi, thanks for this issue.
1. What's your environment - e.g. Droplet, Docker Container or IDE Debug?
I've tested packages in each of them. 
https://github.com/MaxRev-Dev/gdal.netcore/blob/70ab3da2153f8b0679f29092ed358de6de120297/compile/Proj6Configure.cs#L17-L36

2. About framework targeting - that was an intended change, but **we can roll back** that in next version.

**Comment by CropRecords** [comment]
Hi,

1. Visual Studio 2019 16.7 on Windows v2004 in an NUnit test. I pasted that try block in and got for this line:
` if (di.GetDirectories().Any(x => x.Name == sh))`
that 
DirectoryInfo[]' does not contain a definition for 'Any' and no accessible extension method 'Any' accepting a first argument of type 'DirectoryInfo[]' could be found (are you missing a using directive or an assembly reference?)

because I was not referencing System.Linq with
`using System.Linq;`

if you reference Linq then the path seems to calculate correctly to {project}\bin\Debug\netcoreapp3.0\maxrev.gdal.core.libshared

I wonder if the `try` block is jumping to the `catch` because of this perhaps.

2. Thanks, that would be helpful.

**Comment by MaxRev-Dev** [comment]
@CropRecords I have recently added some [XUnit tests](https://github.com/MaxRev-Dev/gdal.netcore/commit/70ab3da2153f8b0679f29092ed358de6de120297), later I will try to reproduce this with NUnit.

About System.Linq reference - it exists in source.
https://github.com/MaxRev-Dev/gdal.netcore/blob/70ab3da2153f8b0679f29092ed358de6de120297/compile/Proj6Configure.cs#L4

**Comment by CropRecords** [comment]
> @CropRecords I have recently added some [XUnit tests](https://github.com/MaxRev-Dev/gdal.netcore/commit/70ab3da2153f8b0679f29092ed358de6de120297), later I will try to reproduce this with NUnit.
> 
> About System.Linq reference - it exists in source.
> https://github.com/MaxRev-Dev/gdal.netcore/blob/70ab3da2153f8b0679f29092ed358de6de120297/compile/Proj6Configure.cs#L4

Yes, I noticed that too when I clicked on the link showing the code. I'm not all that familiar with GitHub.

So I just ran the code again. The PATH then is being combined from e and f which look like:

```
  | Name | Value | Type
  | f | "{project}\\bin\\Debug\\netcoreapp3.0\\maxrev.gdal.core.libshared" | string
  | e | "{project}\\bin\\Debug\\netcoreapp3.0\\maxrev.gdal.core.libshared" | string
```
and so then the PATH is failing because whatever code is copying `proj.db` copies it into `{project}\\bin\\Debug\\netcoreapp3.0` not `{project}\\bin\\Debug\\netcoreapp3.0\\maxrev.gdal.core.libshared`

I was assuming that f was the full `{project}\\bin\\Debug\\netcoreapp3.0\\maxrev.gdal.core.libshared` and that e was `{project}\\bin\\Debug\\netcoreapp3.0` but that's not the case. Maybe that would be a nice-to-have to make it look in the default folder path also.

Regardless I think the main issue is that  `proj.db` needs to be copied to `{project}\\bin\\Debug\\netcoreapp3.0\\maxrev.gdal.core.libshared` and this should solve the issue.

**Comment by MaxRev-Dev** [comment]
Primary, on simple build - if MSBuild did it job well, it does not necessary to copy package sources.
But on in several cases - test hosts or another bootstrappers, package contents structure is used to flatten somehow. 
So I wrote that script to find those contents. The logic is simple:
1. Find location of dynamic libraries using their types (gdal_wrap.dll) + combine it to development project structure `{project}\bin\{configuration}\{tfm}\maxrev.gdal.core.libshared`
2. Or just use root of package - that's a second case.
3. The last is `{projectRoot}/maxrev.gdal.core.libshared`

**Yes**. Here I forgot the case about flatten structure. We should add the project root itself, without subdirectory.
https://github.com/MaxRev-Dev/gdal.netcore/blob/70ab3da2153f8b0679f29092ed358de6de120297/compile/Proj6Configure.cs#L35
<details>
<summary>Package contents</summary>
![image](https://user-images.githubusercontent.com/24393967/89592443-4b938400-d855-11ea-8fcb-5a526e445e04.png)
</details>

**Comment by santoshkaranam** [comment]
I am facing the same proj.dll copy issue in docker. In the final app folder i cannot find the proj.dll
Below is the docker file, i am build image for server2019
----------------------------------------------------------------------------------------
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1809 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809 AS build
WORKDIR /src
COPY ["Sample.API/Sample.API.csproj", "Sample.API/"]
COPY [".nuget","c:/.nuget"]
RUN dotnet restore "Sample.API/Sample.API.csproj" -s "https://api.nuget.org/v3/index.json" -s "c:/.nuget/packages"
COPY . .
WORKDIR "/src/Sample.API"
RUN dotnet build "Sample.API.csproj" -c Release -r win-x64 -o /app/build

FROM build AS publish
RUN dotnet publish "Sample.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Sample.API.dll"]
---------------------------------------------------------------------------------------------
here .nuget folder is local nuget source reference which has nuget for a project where
    <PackageReference Include="MaxRev.Gdal.Core" Version="3.1.0.100" />
    <PackageReference Include="MaxRev.Gdal.WindowsRuntime.Minimal" Version="3.1.0.100" />
are installed.
