### ISSUE TITLE
mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1809 Issue calling registerAll()

### ISSUE THREAD

**Issue by santoshkaranam** [MaxRev-Dev/gdal.netcore#26]
I am facing exception issue when i call registerall() method
System.TypeInitializationException: The type initializer for 'OSGeo.OGR.OgrPINVOKE' threw an exception.

Below is the docker file, i am build image for server2019

----------------------------------------------------------------------------------------
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1809 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809 AS build
WORKDIR /src
COPY ["Sample.API/Sample.API.csproj", "Sample.API/"]
COPY [".nuget","c:/.nuget"]
RUN dotnet restore "Sample.API/Sample.API.csproj" -s "https://api.nuget.org/v3/index.json" -s "c:/.nuget/packages"
COPY . .
WORKDIR "/src/Sample.API"
RUN dotnet build "Sample.API.csproj" -c Release -r win-x64 -o /app/build

FROM build AS publish
RUN dotnet publish "Sample.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Sample.API.dll"]

---------------------------------------------------------------------------------------------

here .nuget folder is local nuget source reference which has nuget for a project where
    MaxRev.Gdal.Core" Version="3.1.0.100"
   MaxRev.Gdal.WindowsRuntime.Minimal" Version="3.1.0.100" 
are installed. 

I even installed above two lib in API project to make sure the proj.dll is copied, which it actullay did, but still i am getting below exception
System.TypeInitializationException: The type initializer for 'OSGeo.OGR.OgrPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'ogr_wrap' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at OSGeo.OGR.OgrPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Ogr(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.OGR.OgrPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.OGR.OgrPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.OGR.OgrPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at OSGeo.OGR.OgrPINVOKE.RegisterAll()
   at OSGeo.OGR.Ogr.RegisterAll()

- i can see gdal_wrap and proj.dll both are there in exe folder

have you tried hosting in nanoserver before?
mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1809

_Originally posted by @santoshkaranam in https://github.com/MaxRev-Dev/gdal.netcore/issues/25#issuecomment-671465794_

**Comment by MaxRev-Dev** [comment]
@santoshkaranam As I wrote [here](#7) it **won't** startup on **nanoserver**.
That's because the nanoserver container does not have VC++ runtime libraries installed (vc_redist.exe).
> To install the correct runtime, you must install the redistributable while building of the docker image.
>As the OP notes in the comments, the microsoft/nanoserver image is sufficient when using static runtime linking, however, if using shared runtime linking, you should use the microsoft/windowsservercore image, otherwise, the installation of the redistributable fails.

This issue is described on SO: https://stackoverflow.com/a/53432272
