### ISSUE TITLE
'./Drawing1.dxf' not recognized as a supported file format.

### ISSUE THREAD

**Issue by Nuan-Yang** [MaxRev-Dev/gdal.netcore#28]
Hello,Author: 
  I recently wanted to convert a DXF file to a GeoJSON file through your GDAL project,But when I use your Linux Mini Runtime, program prompts me for unsupported file types.
Tips are as follows:
  ERROR 4: `./Drawing1.dxf' not recognized as a supported file format.
Is it because the Mini bag does not contain devICED with DXG?

**Comment by MaxRev-Dev** [comment]
DXF is a vector driver and is [built-in by default](https://gdal.org/drivers/vector/dxf.html#vector-dxf). You can open it with Ogr.
`var dataset = Ogr.Open("/path/to/your/file.dxf", 0);`
