### ISSUE TITLE
[BUG] Azure functions - GDAL Can't find proj.db on configuring environment

### ISSUE THREAD

**Issue by YaroslavKormushyn** [MaxRev-Dev/gdal.netcore#43]
**Describe the bug**
`Can't find proj.db.` exception thrown when calling `GdalBase.ConfigureAll()`. The `proj.db` file is present in the `runtimes`, but the method expects it to be under `bin\runtimes`.

**To Reproduce**
Create a sample Function App v3 (`Microsoft.NET.Sdk.Functions 3.0.11`), install the core `MaxRev.Gdal.Core` and runtime `MaxRev.Gdal.WindowsRuntime.Minimal` packages with a `HttpTrigger` function. Call `GdalBase.ConfigureAll();` in the function, call the function.

**Expected behavior**
Exception not thrown, `GdalBase` is configured.

**Screenshots**

<details>
  <summary>Screenshot:</summary>
 
![image](https://user-images.githubusercontent.com/11539004/114890292-8e115580-9e13-11eb-8617-22ff3a4e23b2.png)

</details>

**Environment information:**
 - OS (version): Windows 10 Pro (20H2)
 - Package version (core): 3.2.0.310
 - Package version (runtime): 3.2.0.300

**Additional context**
I've used these configuration calls before and they are working:
```csharp
Gdal.AllRegister();
Ogr.RegisterAll();
```

Here's a zipped solution with the code to reproduce. Just run in debug and hit the `api/GetBasicDxfInfo` endpoint.
[ImportTest.zip](https://github.com/MaxRev-Dev/gdal.netcore/files/6318908/ImportTest.zip)

**Comment by MaxRev-Dev** [comment]
Thanks. Made a PR patch that will close this.
