### ISSUE TITLE
GetProjection returns empty string

### ISSUE THREAD

**Issue by clintsinger** [MaxRev-Dev/gdal.netcore#46]
Hi,

I am loading a raster image (jpg/jgw/prj) and when I call GetProjection() or GetProjectionRef() on the Dataset it comes back with an empty string.  I would have expected something like (in this case) "PROJCS["UTM_Zone_10_Northern_Hemisphere",GEOGCS["GCS_WGS_1984",DATUM["D_WGS84",SPHEROID["WGS84"...".  

Is there some configuration that I am missing or are the functions stubbed out and do nothing?  I have tried on Windows and in a Linux docker container.

The JPEG driver info comes back with only the jpg and jgw in the files list.  Should it be also showing the prj?

Cheers,
Clint

**Comment by clintsinger** [comment]
I tried loading the prj directly and called SetProjection directly on the dataset.   GDAL then created a .aux.xml with the coordinate system information.  The next time it ran it opened up that file directly.   I had used GDAL years ago and I was sure that it could pick up prj files directly. 

I could keep manually injecting the projection this way but it seems like I shouldn't have to.

What is everyone else's experience?

Cheers,
Clint

**Comment by MaxRev-Dev** [comment]
@clintsinger this repo is only a build engine, I mostly work with build tools to create packages. You can always create an issue in [the main repo](https://github.com/OSGeo/gdal/issues).

According to [docs](https://gdal.org/doxygen/classGDALDataset.html#ae6765f379a7ecf38b24c1ff5a06573a7)

> When a projection definition is not available an empty (but not NULL) string is returned.

Please, ensure you have a [valid tiff data](https://github.com/MaxRev-Dev/gdal.netcore/tree/master/test/GdalCore-XUnit/samples-raster).
