### ISSUE TITLE
Azure App Service (Web app) : Receiving runtime exception System.BadImageFormatException with MaxRev.Gdal.Core assembly

### ISSUE THREAD

**Issue by vikramp85** [MaxRev-Dev/gdal.netcore#51]
Hi Team,

We have a .NET 5.0 web api application that leverages the following Gdal Core packages:

    <PackageReference Include="MaxRev.Gdal.Core" Version="3.2.0.320"/>
    <PackageReference Include="MaxRev.Gdal.WindowsRuntime.Minimal" Version="3.2.0.300"/>

The application compiles and runs successfully in our local development environment  (Visual Studio Code, Windows 10 Enterprise). However, when it's packaged and published to an Azure app service (web app) it yields the following runtime exception:

System.BadImageFormatException 1
Could not load file or assembly 'MaxRev.Gdal.Core, Version=3.2.0.319, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

The said assembly, MaxRev.Gdal.WindowsRuntime.Minimal.dll & other runtime native assemblies were packaged and are present in the Azure app service backend (Kudu- wwwroot directory) once deployed. Also, Azure App service and solution project (.csproj) are both targeting to .net5.0.

Are we missing any build configuration while packaging which could be causing this issue in Azure on deployment?

**Comment by MaxRev-Dev** [comment]
Have not faced this issue before. Have you tried to delete deployment files manually as pointed in azure deployment [error reference](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-iis-errors-reference?view=aspnetcore-2.1#platform-conflicts-with-rid-1)?

**Comment by vpatil85** [comment]
Just to rule this out, we did spin up a new Azure app instance altogether in a separate region and performed a new deployment which resulted in the same issue.

On the other hand, in addition to VS Code hosting (dotnet run), we also hosted the published package content in an independent website within the local IIS (IIS 10, Windows 10) and it returned a success response.

**Comment by MaxRev-Dev** [comment]
Interesting. The latest version do run in ordinary environment (netcoreapp3.1), but not isolated one (net5.0).  I had fixed some path issues in https://github.com/MaxRev-Dev/gdal.netcore/issues/43 for Azure Functions, so in some way they do work. 
I'm not sure about looking for advanced build settings in MSBuild, as we are creating packages with simple `dotnet pack` command. 
Can you provide a minimal repro project?

**Comment by vikramp85** [comment]
Hi MaxRev,

The issue happened because of a mismatch in the build version (32 bit vs 64 bit). 

There is a property in our .Net Core project (.csproj) - <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel> that was causing the Azure app service's runtime switched to 32 bit even if it is explicitly set to 64 bit under Azure App Service > Configuration > Platform Settings

In short, the platform settings on the app service were getting overridden and defaulted to 32 bit when this configuration is in place.

Switching to <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel> has resolved the issue. We have reported this behavior to MS support to seek their inputs on what seems like a potential bug.

Since this is totally unrelated to Gdal Core packages, we may close this issue.
Thanks for all your help.
