### ISSUE TITLE
[BUG] Inconsistent gdal dll version name in MaxRev.Gdal.Core.WindowsRuntime 3.2.0.300

### ISSUE THREAD

**Issue by jugstalt** [MaxRev-Dev/gdal.netcore#52]
Hi,
first of all great job. To have all the native dependencies for GDAL with C# bindigs in a nuget package is very very usefull.
I testet it and it works!

But one little thing:
I need support for ECW and JPG2000 on Windows. I dont want to compile it by myself and downloaded binaries from gisinternals.com.
Then i copied

gdalplugins/gdal_ECW_JP2ECW.dll
libecwj2.dll

to the native/win-x64 directory in my solution. The Plugin is compiled vor GDAL 3.2.0 (same as your dlls)
But it did not work, becuase gdal_ECW_JP2ECW.dll depends on gdal302.dll. Your dlls name is gdal301.dll ;)

I also tried to use the gdal_ECW_JP2ECW.dll for GDAL 3.1.0. In this case Gdal.RegisterAll() complains, that the Version gdal_ECW_JP2ECW.dll is compiled for a wrong version of GDAL (witch is the correct answer anyway).

In your gdal_nmake.opt you have defined VERSION = 301.
Can you please change this to the right Version (302), next time you publish the package to nuget?

Thanks!

**Comment by MaxRev-Dev** [comment]
It is not as simple as you think. You can not just add DLLs to folder to add a specific driver. To add those drivers entire bindings should be recompiled (C# SWIG bindings in MaxRev.Gdal.Core package). The GDAL's version also does not matter. 
I can not tell you how long it can take to compile the next version, because I have several large tasks to be done at work.

**Comment by jugstalt** [comment]
Ok, its not a big and urgend Problem.

But for your Info: If the plugins match with the GDAL Version, its easy possible to add them to the solution. As long as all depencies from the plugin are also included in the solution (gdal_ECW_JP2ECW.dll also needs libecwj2dll for example). 

I am currently use your nuget package (MaxRev.Gdal.WindowsRuntime.Minimal 3.1,x) with the ECW plugins compiled for GDAL 3.1 and it works like a charm.

But i can not use 3.2 because the dpendency gdal_ECW_JP2ECW.dll => gdal302.dll is missing. So i think, if you change the version in your gdal_nmake.opt to 302 it will also work with GDAL 3.2 for me.

**Comment by MaxRev-Dev** [comment]
Converting this back to be more precise with context of this issue. 
Currently, we can't add ECW and JPEG2000 drivers, that requires additional SDK installation with complex download or alternatively we should find the binaries to include in project.
