### ISSUE TITLE
Error reading UTF-8 shapefile

### ISSUE THREAD

**Issue by aminabbasi604** [MaxRev-Dev/gdal.netcore#54]
can't read shapefile utf8

on linux centos 7 

![23](https://user-images.githubusercontent.com/44006931/129891271-299afb53-e1c7-46cb-958f-5c94a54ea636.png)

**Comment by MaxRev-Dev** [comment]
@aminabbasi604 Please, do check your file source.
As I see, you can read your file and it seems like there's a broken file structure. The first symbol is actually a UTF-8 letter.

Please, use issue templates and provide descriptive information about your problem.
![image](https://user-images.githubusercontent.com/24393967/129896676-4e8abd85-c599-4dec-b2d0-bc718a947030.png)

**Comment by aminabbasi604** [comment]
Thanks for the answer, but my problem is that when I want to read the shape file of their data, I come across this.

**Comment by MaxRev-Dev** [comment]
I don't know which version of packages you are using and what data you are reading.
But similar issue (truncated, malformed symbols) was resolved in PR #29.

**Comment by aminabbasi604** [comment]
thanks my problem solved
