### ISSUE TITLE
GDAL 3.3.3  support

### ISSUE THREAD

**Issue by anton-petrov** [MaxRev-Dev/gdal.netcore#56]
Hi, @MaxRev-Dev ! Thank you for your awesome work for supporting GDAL/C# :)

When is the new version release expected?

**Comment by MaxRev-Dev** [comment]
Will try to deliver them ASAP. Both builds are almost ready. I'm currently experimenting with external libtiff in order to close #30.

**Comment by MaxRev-Dev** [comment]
Happy holidays. It took some time but the release is ready. Feel free to [discuss it.](https://github.com/MaxRev-Dev/gdal.netcore/discussions/65)
