### ISSUE TITLE
Is Gdal.VSIFReadL not supported?

### ISSUE THREAD

**Issue by adiletelf** [MaxRev-Dev/gdal.netcore#57]
**Is your feature request related to a problem? Please describe.**
<Can't read a file with the path `/vsimem/Data/filename.mif` as byte[].>

**Describe the solution you'd like or your ideas here**
<  Add support for Gdal.VSIFReadL please >

**Additional context**
I use /vsimem/ file system to create Mapinfo files in-memory but I couldn't find a way to retrieve file without creating a local file.
```
var vsiFile = Gdal.VSIFOpenL(filePath, "r");

Gdal.VSIFSeekL(vsiFile, 0, 2);
var size = Gdal.VSIFTellL(vsiFile);
Gdal.VSIFSeekL(vsiFile, 0, 0);

var data = new byte[size];
// Gdal doesn't have VSIFReadL 😢 
// Gdal.VSIFReadL(data, size, 1, vsiFile);
return data;
```

````markdown
<details>
  <summary>
![image](https://user-images.githubusercontent.com/74559101/142561681-04cdab11-f25e-43a5-bb3a-ce1070766778.png)
</summary>
  [link](to)
</details>
````

**Comment by adiletelf** [comment]
[VSIGetMemFileBuffer](https://gdal.org/doxygen/cpl__vsi_8h.html#aeaf26bcc4a5314371f426bb2a5e6ce7a) is not supported too 😿 
If I am being stupid and there's solution I would be very grateful to hear it!

P.S. It's possible to copy the file to actual file system but then there's no point in using /vsimem/.

**Comment by MaxRev-Dev** [comment]
No, it's not supported, and won't be implemented in this repo. Everything comes from SWIG interface in GDAL.
If you need this functionality, please create an issue in the [main repository](https://github.com/OSGeo/gdal) of GDAL.

Source that handles definition of this method:
https://github.com/OSGeo/gdal/blob/0cf797ecaa5d1d3312f3a9f51a266cd3f9d02fb5/swig/include/cpl.i#L808-L811
