### ISSUE TITLE
[BUG] Can't run GdalBase.ConfigureAll() from a Windows app installed in Program Files without admin rights

### ISSUE THREAD

**Issue by marconian** [MaxRev-Dev/gdal.netcore#59]
**Describe the bug**
When running GdalBase.ConfigureAll() from a .NET application installed in the Windows 'Program Files' directory the application throws an UnauthorizedAccessException due to the lack of rights when running as a normal user. 
ConfigureAll() always tries to create a directory in the executing assembly directory, even if it already exists. 

**To Reproduce**
Create a simple Windows console application with only 'GdalBase.ConfigureAll()'. Build the application and disable write access on the application folder for the current user. Then run without elevated access to reproduce.

**Expected behavior**
GdalBase.ConfigureAll() should check if the directories and files already exist. If so then it should skip creation.

**Environment information:**
 - OS (version): Windows 10 Enterprise(21H1)
 - Package version (core): 3.2.0.320
 - Package version (runtime): 3.2.0.310

**Comment by NVilenski** [comment]
Hello, I'm using this library on server side and we have the same issue with the second mode of the usage (when library tries to find GDAL_*.dll files in the environment folder and if found - each time tries to copy or recreate it into the gdalplugins folder). This way libraries are locked by the first instance of application and we get error on second instance start.
We've found the way to avoid it by publishing application in the portable mode (so all related GDAL_*.dll libraries are placed in the runtimes folder) but it makes result package too large.
Could you please apply the same approach to this situation? Like if we already have libraries in the /gdalplugins folder then do not recreate it again. Or may be use some additional argument for ConfigureAll() like 'bool recreateLibraries' or something like this?

**Comment by MaxRev-Dev** [comment]
@NVilenski Please checkout the patched package `Install-Package MaxRev.Gdal.Core -Version 3.3.3.120 `

**Comment by NVilenski** [comment]
> @NVilenski Please checkout the patched package `Install-Package MaxRev.Gdal.Core -Version 3.3.3.120 `

Thank you! This one works great!
