### ISSUE TITLE
Need to do an append instead of an OVERWRITE

### ISSUE THREAD

**Issue by elisamendezcaceres** [MaxRev-Dev/gdal.netcore#75]
Hi, 
I'm using this package , and I want to import a shape into a table that already exists in a Postgres database with the CopyLayer() function, but it gives me an error saying that I must put OVERWRITE=YES. I need to do an append instead of an OVERWRITE. I've tried several options but it doesn't work. What I can be doing wrong?. This is the code:

```
var gmlDriver = OSGeo.OGR.Ogr.GetDriverByName("ESRI Shapefile");

var dsGml = gmlDriver.Open(shapeFile, 0);
				
var buildingLayer = ogrPostgres.CopyLayer(layer,table,options)

var ogrPostgres = OSGeo.OGR.Ogr.Open("PG:dbname=db password=pass user=usr-gis host=locahost", 0);

for (int iLayer = 0; iLayer < dsGml.GetLayerCount(); iLayer++)
{
    Layer layer = dsGml.GetLayerByIndex(iLayer);
    
    string[] options = new string[] {  
        "GEOMETRY_NAME=geom",
        "FID=gid"
    };
    
    var buildingLayer = ogrPostgres.CopyLayer(layer,table,options);       

    buildingLayer.StartTransaction();
    buildingLayer.CommitTransaction();                    
}
```

Thanks.

**Comment by MaxRev-Dev** [comment]
I don't know a lot about this API, but in order to update dataset you must pass `1` as a second parameter to the static function - `Ogr.Open("<connection string>", 1);`

Also you should search of an issue or leave a new one in the [official repository of GDAL.](https://github.com/OSGeo/gdal/issues)
