### ISSUE TITLE
Different Output for S-57 Data on Windows and Linux

### ISSUE THREAD

**Issue by tylercwiltz** [MaxRev-Dev/gdal.netcore#76]
I'm working with some S-57 Data and I loop through the features of each layer and then call DumpReadable() on each feature.  For windows I get an output I would expect, but when I run it on Linux (Ubuntu 20.04) I get a different output.  The feature names are different and there are less attributes per feature than in Windows.  I'm using .Core 3.3.3.120 and .WindowsRuntime.Minimal 3.3.3.110 for Windows and the .Core 3.3.3.120 and .LinuxRuntime.Minimal 3.3.120 for Linux.  Has differing outputs on different OS been an issue?

**Comment by MaxRev-Dev** [comment]
We are not able to change this. This issue is related to internal methods GDAL.
If you have any further questions, consider opening an issue in the [GDAL repository](https://github.com/OSGeo/gdal/issues).
