### ISSUE TITLE
Read file streams in addition to file paths

### ISSUE THREAD

**Issue by sirhcybe** [MaxRev-Dev/gdal.netcore#77]
I would like to use this library in conjunction with a web application where a user can upload a GeoDatabase. When they do that in ASP.NET Core the file comes in as an IFile object that contains a stream. The way this library currently works is that it requires the file to exist on the filesystem before it can be opened so I have to save the file to the file system from the stream before using it.

Ideally I would simply be able to pass this stream into the OSGeo.OGR.Driver.Open method instead of a file path. This would eliminate the I/O constrained step of writing to and reading from the filesystem from my code, reduce security concerns around saving uploaded files to the web server, and make my implementation cleaner and more maintainable.

Looking through the source it looks like this may require changes to the underlying GDAL library? I'm not skilled enough in C++ to know how to make this happen myself.

**Comment by MaxRev-Dev** [comment]
Not sure If I can help. As I stated in main readme - this library does not extend GDAL methods in any way.
But GDAL itself has a `vsimem` driver that allows reading virtual filesystem sources.
https://gdal.org/user/virtual_file_systems.html
You can try to copy your IFormFile into a memory buffer and then open it with vsimem driver. There is an example in gdal apps. 
https://trac.osgeo.org/gdal/browser/trunk/gdal/swig/csharp/apps/VSIMem.cs
