### ISSUE TITLE
Run -update -append ... -lco "OVERWRITE=YES" with GDAL.Netcore?

### ISSUE THREAD

**Issue by driekus77** [MaxRev-Dev/gdal.netcore#80]
I've created a GDAL.Netcore related question on Stackoverflow: https://stackoverflow.com/questions/74730712/how-to-run-ogr2ogr-copy-from-gml-to-postgres-from-gdal-netcore-library-c

So far without any reaction(s) so posting the question hier also.

The bottom-line is I want to run the following command-line ogr2ogr from within our C# code:
```sh
ogr2ogr -update -append PG:"dbname='postgres' host='***' port='5432' user='***' password='***' -f XML mygml.xml -lco SCHEMA=myschema -lco OVERWRITE=yes
```

Is this possible with the current GDAL.Netcore version? If so can anyone point me in the right direction?

Thanks!

**Comment by MaxRev-Dev** [comment]
First of all, this is not related to MaxRev.Gdal.Core bindings. This repo only provides compiled packages for GDAL. All of the samples you can find in the [**GDAL**](https://github.com/OSGeo/gdal/tree/master/swig/csharp/apps) repository.
I've added a few useful links for upcoming [release](https://github.com/MaxRev-Dev/gdal.netcore/tree/v3.6.0#using-gdal-functions). If you can't find any suitable sample and there is a problem with API, please, leave an issue in the [GDAL repo](https://github.com/OSGeo/gdal/issues).

> Here's a good place to start:
 > - [Vector related operations](https://github.com/OSGeo/gdal/tree/master/doc/source/api/csharp/csharp_vector.rst)
 > - [Raster related operations](https://github.com/OSGeo/gdal/tree/master/doc/source/api/csharp/csharp_raster.rst)
 > - [Sample Apps](https://github.com/OSGeo/gdal/tree/master/swig/csharp/apps)
