### ISSUE TITLE
Cannot find grib2_subcenter.csv after upgrade to 3.6.1

### ISSUE THREAD

**Issue by sokolik745** [MaxRev-Dev/gdal.netcore#91]
I am migrating our backend app to .NET 7 and I updated MaxRev.Gdal.Core and MaxRev.Gdal.LinuxRuntime.Minimal packages to the newest version 3.6.1.100. After this upgrade I am getting this error on jammy linux distribution: 
`System.ApplicationException: Cannot find grib2_subcenter.csv
   at OSGeo.GDAL.Gdal.Open (MaxRev.Gdal.Core, Version=3.6.1.100, Culture=neutral, PublicKeyToken=null)`

I listed the files and folders in the pod and I can't find any data files where could be the grib2_subcenter.csv file located according to [this](https://github.com/OSGeo/gdal/blob/master/gdal.cmake). I cant find any path `runtimes/linux-x64/native/` either which is defined [here](https://github.com/MaxRev-Dev/gdal.netcore/blob/master/gdalcore.linuxruntime.csproj).

The code is just trying to open this file [raster.zip](https://github.com/MaxRev-Dev/gdal.netcore/files/10674920/raster.zip). I am not sure why this is happening because this file is not grib file. 

It is working fine when it runs on Windows.

 - OS (version): jammy (ubuntu 22.04)
 - Package version (core): 3.6.1.100
 - Package version (runtime): 3.6.1.100

**Comment by MaxRev-Dev** [comment]
It seems like a part of your code is using the [GRIB driver](https://gdal.org/drivers/raster/grib.html#configuration-options), which requires the GDAL_DATA folder (or GRIB_RESOURCE_DIR) to be present. This was broken only in our latest version, 3.6.1, according to the [changelog](https://github.com/OSGeo/gdal/blob/master/NEWS.md#new-installed-files-1). 

By default, this package only provides a PROJ database (grid shifts). Nothing from the GDAL_DATA folder was packaged before.
I can introduce a patch soon to include grids and other data files in the Core package.

As a temporary workaround, you can download the [gdal/data](https://github.com/OSGeo/gdal/tree/master/data) folder and set the environment variable (GDAL_DATA) to match this folder.

**Comment by sokolik745** [comment]
Thank you for your quick reply I appreciate it. It would be great to have an updated package but we will try the workaround in the meanwhile.

**Comment by sokolik745** [comment]
It seems that the proposed workaround is not working. I copied the gdal data and set the environment variable as you can see here: 
![image](https://user-images.githubusercontent.com/22426839/217554210-e207cd35-6ce0-4cea-9b9a-5fa3fd74bc97.png)
![image](https://user-images.githubusercontent.com/22426839/217554782-5be7b119-1eca-484b-add3-e14a6c3759a8.png)
It is still not working. Am I missing something?

**Comment by MaxRev-Dev** [comment]
Yes. You did not set the environment variable correctly to point to that folder.
`echo $GDAL_DATA`

**Comment by sokolik745** [comment]
Sorry, my mistake. Wrong screenshot. The environment variable is set to this:
![image](https://user-images.githubusercontent.com/22426839/217558010-b4129c76-ccaa-4330-974f-8a97f90bd000.png)

**Comment by MaxRev-Dev** [comment]
You can also try to set it as a config option with
`Gdal.SetConfigOption("GDAL_DATA", path)`

**Comment by sokolik745** [comment]
Unfortunately I am not able to get it work either. Maybe we will just wait for the new version of package. Or do you have any other suggestions? Thanks!

**Comment by MaxRev-Dev** [comment]
Here you go:
[gdal-grib-repro.zip](https://github.com/MaxRev-Dev/gdal.netcore/files/10696757/gdal-grib-repro.zip)
1. Without a defined GDAL_DATA path
2. And after setting a config option
![image](https://user-images.githubusercontent.com/24393967/217807939-ab8ec066-0f55-4998-af56-b844a7e706c3.png)

**Comment by sokolik745** [comment]
Nice it works. Our problem was in pipelines and your solution is working. Thank you!
