### ISSUE TITLE
Check Geometry Validity

### ISSUE THREAD

**Issue by sindizzy** [MaxRev-Dev/gdal.netcore#93]
First, thank you for bringing this to GitHub. I have already incorporated your package into one of my apps.
It works great and has all the functions I need.

One thing that I am looking for is determining the reasons a geometry is not valid. Currently there is the Geometry.IsValid but that's just a true/false. There's also a MakeValid which you can use to make an invalid geometry valid. Those are great but what I'm after is a CheckValid function that tells you the reasons the geometry didn't pass the grade. Something like:
```
  "Self-interesecting nodes"
  "Linestring must be closed"
  "Null coordinates"
  etc
```
Is there such a thing in GDAL/OGR?

**Comment by MaxRev-Dev** [comment]
As far as I know, GDAL MakeValid does not have such API. You can use NTS for this https://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Operation.Valid.IsValidOp.html#NetTopologySuite_Operation_Valid_IsValidOp_ValidationError

**Comment by sindizzy** [comment]
Excellent. Ill give that a try.
Thanks!
